neoclide/coc.nvim

rplugin/python3/denite/source/service.py
=> fix coc-service source list highlight

src/source/gocode.ts
shouldComplete needs to return value.
=> fix gocode shouldComplete check

src/extensions.ts
=> fix: valid ext check

data/schema.json, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/buffer.ts, src/diagnostic/manager.ts
solves: https://github.com/neoclide/coc.nvim/issues/360
Uses NeoVim virtual text to display diagnostics.
`"coc.preferences.diagnostic.virtualText"` defaults to `false`.
=> Implement NeoVim virtual text diagnostics

src/diagnostic/buffer.ts
Autocomplete must have added this
=> Remove unneeded dependency

src/languages.ts
https://github.com/neoclide/coc.nvim/issues/373
=> fix(completion): correct cursor placement after additional edits

src/provider/hoverManager.ts
it will be great to get the rest hover info if the higher score provider have no hover info.
=> add multiple hover provider support

Readme.md
Solve install and using coc.nvim in nixos:
https://github.com/neoclide/coc.nvim/issues/559
=> Update README.md for nixos users.

Readme.md
https://github.com/bmewburn/intelephense-server is broken.
=> fix: intelephense docs link

src/language-client/index.ts, src/services.ts
relative issue https://github.com/neoclide/coc.nvim/issues/650
=> fix lsp command start with "~"

src/handler/index.ts
work with ruby and got `sym.range` undefined.
=> fix range not always exists

Readme.md
Hey,
I just stumbled upon this project through reddit, and I am planning on using it. I spotted some grammatical mistakes while browsing through the readme, so i figured I could help out a bit by fixing them.
=> Fixed some of the gramatical errors in the Readme.md

Readme.md
I've been really impressed with Coc so far! Thanks for all the effort that has gone into this project!
I went through the readme and made quite a few small grammar changes just to help it read a bit better. Feel free to change anything that you might not like.
Cheers!
=> Readme grammar updates

Readme.md
I made a bad edit and this PR cleans it up.
=> cleanup Readme.md

data/schema.json, doc/coc.txt
Great job with coc! I was reading the doc and found this typo.
=> Fix some typo in doc

src/diagnostic/buffer.ts
Fix to allow different Coc*Sign and Coc*VirtualText highlights.
=> fix(virtualtext): invalid highlight tag

Readme.md
👋 This PR removes a duplicated entry for **Elm** in the Readme file.
=> Remove duplicated Elm entry

Readme.md
Extremely minor, thanks for the plugin!
=> docs: fixed internal link in readme

data/schema.json, src/model/extension.ts
=> feat(extension): add proxy auth support

autoload/coc/util.vim, doc/coc.txt
`let g:coc_extension_root='balabala'`
=> allow customize extension root

plugin/coc.vim
=> fix: parse ansi code error

src/list/source/folders.ts
For issue #1022 
Adds 'newfile' action on folders list
=> [RFC] Allows creating files from folders list

doc/coc.txt
Hi!
This is just a tiny documentation fix. It's my first PR, so please let me know if I should change something :)
Marius
=> Fix duplicate default value in documentation of suggest.enablePreview

doc/coc.cnx, doc/coc.txt
coc-setting.json > coc-settings.json
=> Fix settings filename in docs

src/workspace.ts
This should solve the issue #1006
=> Fixed the doHover CocAction under cygwin

src/languages.ts
=> feat(languages): formatOnSave for all filetypes

autoload/coc/util.vim, src/handler/colors.ts
And fix `osascript` / `set_current_alpha` range to 0-65535
Zenity is included in most linux distributions
=> feat(highlight): Pick color by zenity

src/model/download.ts, src/model/fetch.ts
close #1115, code from requests.js: https://github.com/request/request/pull/1096/files#diff-ccc0734f65dd7a299409ff07d35be095
=> feat(fetch): respect to no_proxy env

data/schema.json, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/manager.ts
=> feat(diagnostic): configurable delay for diagnostic display

data/schema.json, src/languages.ts, src/util/complete.ts
https://github.com/neoclide/coc.nvim/issues/1187
=> feat(completion): add suggest.invalidInsertCharacters

src/list/source/commands.ts, src/list/source/lists.ts, src/list/source/services.ts, src/list/source/sources.ts, src/services.ts
=> fixed typo, registed to registered

data/schema.json, src/completion/complete.ts, src/completion/index.ts, src/types.ts
added option to change default behavior for sorting
which is by length.
there is currently one other option `alphabetical`
Closes #1070
=> feat(completion): add suggest.completionDefaultSortMethod

Readme.md
=> Fixed backers images alignments

Backers.md, Readme.md
details has been moved to wiki pages, make them easy to edit.
close #923
=> chore(README): cleanup README

src/diagnostic/manager.ts, src/plugin.ts
Add two more Plug commands for a case when you want to build code & jump
to the first found error.
=> add coc-diagnostic-first and coc-diagnostic-first-error

src/languages.ts
coc-java is use item.textEdit.newText Snippet
=> fix coc-java newText Snippet fail

src/languages.ts
Reverts neoclide/coc.nvim#1429
=> Revert "fix coc-java newText Snippet fail"

data/schema.json, src/completion/complete.ts, src/completion/index.ts, src/types.ts
close #1459
**default false**
~cc @chemzqm I make `suggest.asciiCharactersOnly` default true, any suggestions?~
=> feat(suggest): suggest.asciiCharactersOnly option

README.md
Elaborate on suggested options for the plugin configuration and refine the wording.
=> NFC: Refine README documentation

src/language-client/client.ts, src/languages.ts
Reverts neoclide/coc.nvim#1565
=> Revert "fix(completion): support allCommitCharacters as fallback for commitCharacters"

src/language-client/client.ts, src/languages.ts
Reverts neoclide/coc.nvim#1569
=> Revert "Revert "fix(completion): support allCommitCharacters as fallback for commitCharacters""

doc/coc.cnx, doc/coc.txt
This patch is a mix of formatting and readability improvements in the documentation.
=> Improve formatting and refine wording in Vim docs

src/list/manager.ts
=> fix(help): avoid polluting q nmap

autoload/coc/util.vim
Fixing a typo in error message
=> Fix typo termnial -> terminal

src/diagnostic/collection.ts
This PR cleans up the implementation of `DiagnosticCollection.set()` in `src/diagnostic/collection.ts`.
This eliminates the recursive call of the `(uri: string, diagnostics: Diagnostic[] | null)` overload when originally calling using the `(entries: [string, Diagnostic[] | null][])` overload.
The main change is wrapping the `uri`, `diagnostics` pair into an array `[[uri, diagnostics]]` and then continuing on as if the `entries` overload was called.
This change reduces the complexity of the function and eliminates some nesting and null-checking since it can be done up-front when processing the `entries` array.
=> refactor(diagnostic): clean up DiagnosticCollection.set()

src/handler/codelens.ts
FYI https://github.com/neoclide/coc.nvim/pull/1747#issuecomment-612552694
=> fix(codelens): typo

src/model/outputChannel.ts, src/types.ts
https://github.com/fannheyward/coc-rust-analyzer/issues/98
=> feat(model): clear output when larger than MAX_STRING_LENGTH

autoload/coc/client.vim
=> fix(client): var define error

src/services.ts
=> feat(language-client): expand homedir

src/diagnostic/manager.ts, src/model/floatFactory.ts
The diagnostic floating window will be closed immediately while jumping into it using <C-w>p.
=> fix(diagnostic): fix can not jump into diagnostic window

README.md, doc/coc.txt
Documents feature provided by https://github.com/neoclide/coc.nvim/pull/1870
=> Document coc-classobj-* textobj

README.md
Recent vim can merge signcolumn and number column into one
=> Use set signcolumn=number if available

README.md
=> DOC: fix comment error in example vim config

src/plugin.ts
Promise wasn't being returned which meant actions like CocAction("commands") weren't returning any result
=> Return promise in cocAction

README.md
Previously: ...By use yarn
Now: ...By using yarn
=> Fix grammar in code snippet in README.md

autoload/coc/util.vim
=> Call `expand()` only on node's path

src/provider/workspaceSymbolsManager.ts
=> ignore null symbol response

.github/FUNDING.yml
=> Remove duplicate Patreon

doc/coc.cnx, doc/coc.txt
=> chore: update docs

src/completion/complete.ts
See debug info #2250 (comment)
=> Guard typeof item is object. Fix issue #2250

src/list/source/commands.ts
BREAKING CHANGE: `CocList commands` will list workspace commands only.
close #2290
=> feat: list workspace commands only

src/language-client/index.ts
Object.assign later sources will overwrite earlier ones.
=> fix: LS env should overwrite process env

src/diagnostic/manager.ts
https://github.com/neoclide/coc.nvim/commit/c83813f73007d00d5590495d8d6420ad3ded632d#diff-63c0050a3ae34f911430e2896f82a75fL131
=> fix: checkSigns on buffer write

autoload/coc/api.vim
=> Fix duplicated diagnostics after undo

src/model/floatBuffer.ts
=> chore: trim code block for nvim only

src/__tests__/modules/workspace.test.ts, src/workspace.ts
=> fix: create file if parent folder not exist

src/list/source/outline.ts
=> feat: add identation marks for outline list

src/model/floatFactory.ts
=> fix(float): only close border window if it exists, fix #2462

src/extensions.ts
```
Error on CursorMoved: Cannot read property 'length' of undefined
```
=> fix error message in cocupdate panel.

data/schema.json, src/diagnostic/manager.ts
The configuration names came from https://github.com/microsoft/vscode/blob/2d8bbc6976748c4b0c5e84be541674b89b9d91e4/src/vs/monaco.d.ts#L4063-L4064
=> feat(diagnostic): filter unused/deprecated diagnostics

README.md, doc/coc.cnx, doc/coc.txt
=> docs: use release as default branch

src/completion/index.ts
close #2594
@chemzqm completion/floating removed the `enable` config, so I just check before `show`.
=> fix(completion): only floating on floatEnablecommit

src/handler/codelens.ts
Fixes https://github.com/haskell/haskell-language-server/issues/618
Fixes https://github.com/neoclide/coc.nvim/issues/2643#issue-748962009
=> Join lines in code lenses

autoload/coc/rpc.vim, autoload/coc/util.vim
https://github.com/weirongxu/coc-explorer/issues/326
https://github.com/weirongxu/coc-explorer/blob/942152abc7907a0a82ce364bc50a4a463a6e925c/src/util/ui.ts#L130-L133
=> fix: Fixed not enough arguments for util#with_callback a:cb

.github/workflows/ci.yml
latest nvim nightly needs GLIBC_2.29
=> fix(github): use ubuntu-20.04

src/model/progress.ts
Used in https://github.com/neoclide/coc.nvim/blob/51f000b9e0cc72d85aa144045e3d9486db3f3985/src/model/progress.ts#L59
=> fix(model): missing logger

src/handler/index.ts
Give floatActions setting. If false, using quickpick
=> add handle floatActions

src/__tests__/modules/extensions.test.ts, src/extensions.ts, src/model/installer.ts
=> fix(installer): install scoped extensions

src/handler/index.ts
Fixes #2871 
@chemzqm Let me know if this fix would be acceptable or if you would want something more elaborate like adding a parameter to configure this (or a preference maybe)
=> Always apply code action if one specific action is requested

esbuild.js, package.json, yarn.lock
=> feat(esbuild): watch mode

doc/coc.txt, plugin/coc.vim, src/workspace.ts
=> feat(handler): coc-codeaction-cursor

src/handler/index.ts
=> fix(handler): doQuickfix for current line

data/schema.json, doc/coc.txt, src/workspace.ts
Fixes issues with slower linters.
=> Add willSaveHandlerTimeout config

autoload/coc/float.vim
related commit: fedaf52837f6e62d51f91083dd801b0741db1ad3
=> fix #2963 for vim

src/handler/refactor/index.ts
It will occur errors when edit relative buffer after close refactor buffer.
=> fix(refactor): fix refactor buffer does not dispose

src/handler/index.ts, src/plugin.ts
- `CocAction('definitions')`
- `CocAction('references')`
https://github.com/fannheyward/telescope-coc.nvim
=> feat(handler): output references/definitions

src/__tests__/modules/workspace.test.ts, src/workspace.ts
revert 5699963
close #3037
related #2203
=> fix(workspace): do not merge documentChanges edits

src/handler/index.ts, src/plugin.ts
=> feat(handler): implementations/declarations/typeDefinitions

src/__tests__/modules/extensions.test.ts, src/model/installer.ts
close #3075
`CocInstall https://github.com/sdras/vue-vscode-snippets@main`
=> feat: install extension from url with branch

src/workspace.ts
=> fix(workspace): check doc.uri equal or not

data/schema.json
https://github.com/neoclide/coc.nvim/issues/3103
=> (docs)schema: allow custom coc.preferences.jumpCommand values

package.json, src/main.ts, yarn.lock
=> fix: remove polyfill of Promise.prototyp.finally

src/handler/search.ts
=> fix(search): rg 13.0.0 needs root path to work

src/language-client/client.ts, typings/index.d.ts
CallHierarchyMiddleware
SemanticTokensMiddleware
LinkedEditingRangeMiddleware
RegistrationType
RequestType
=> feat(typings): more typings

data/schema.json, src/source/file.ts
Add windows driver path support to fix #1581
=> fix(source/file): add windows driver(X:\ or X:/) path support

autoload/coc/highlight.vim, src/__tests__/handler/semanticTokens.test.ts, src/handler/semanticTokensHighlights/buffer.ts, src/handler/semanticTokensHighlights/index.ts
1. use HighlightItem
2. format showSemanticHighlightInfo
=> feat(handler): use HighlightItem

src/handler/index.ts
sorry for the lint error in https://github.com/neoclide/coc.nvim/pull/3223
=> fix(handler): lint

src/provider/signatureManager.ts
[coc-clojure](https://github.com/noahtheduke/coc-clojure) uses spaces.
=> Allow whitespace as trigger characters

src/handler/locations.ts
The doc says return false when location not found. But that's not the truth
=> fix(locations): Correct the return result of goto functions

src/handler/semanticTokensHighlights/index.ts
=> fix(semanticTokens): remove duplicate type

src/completion/complete.ts
closes https://github.com/fannheyward/coc-rust-analyzer/issues/855
=> fix(completion): don't preselect for empty input

doc/coc.txt
Incremental documentation improvements: enforce column width, slightly improve wording, expand some not commonly used abbreviations.
=> docs(doc): Stylistic documentation fixes

autoload/coc/util.vim
https://github.com/neoclide/coc.nvim/issues/3044#issuecomment-887332974
=> fix(util.vim): keep jumplist for jump with drop

src/diagnostic/manager.ts
=> fix(diagnostic): diagnostic.format.replace

doc/coc.txt, src/handler/locations.ts, src/plugin.ts
`:call CocAction('references', v:false)`
=> feat(handler): references with includeDeclaration

plugin/coc.vim, src/handler/locations.ts
make CocLocations return bool like CocAction('jumpDefinition') etc
=> make CocLocations return bool

plugin/coc.vim
make `CocLocationsAsync` call `AsyncRequest` so that it supports callback
=> make CocLocationsAsync support callback by calling AsyncRequest instead

README.md
First of all, thank you for the amazing vim plugin.
I know I'm a little bit cheeky, but recently I've started to donate my money to this project, so it's my pleasure to be listed on Backers of README.
Thanks!
=> Add backers (including me)

data/schema.json, src/__tests__/completion/basic.test.ts, src/completion/complete.ts, src/completion/index.ts
=> feat(completion): add suggest.ignoreRegexps

src/list/manager.ts
Motivation:
I want to port result from `CocAction('listLoadItems', 'typos')` to quickfix and found that the source is `ListTask`.
If don't care the sink handler is in coc-extension or in Neo/vim, adding API for coc-extensions is better. The extension can get the ListTask and handle data by itself.  It's related to https://github.com/neoclide/coc.nvim/pull/3752 .
=> fix(list): support ListTask for listLoadItems action

README.md
I don't have a great explanation of why, but I feel the old logo could be improved.
If the PR is unwanted, there isn't a problem, it was just an idea I had. You can close it freely.
=> Change project logo

README.md
=> chore(README): GitHub format

src/handler/inlayHint/buffer.ts
=> chore(inlayhint): use combine hl_mode

autoload/coc/util.vim
=> fix(files): use workaround for URI-like path only

src/completion/pum.ts
Should only check for existence here
=> fix(pum): use `in` to check if property exists

data/schema.json, doc/coc-config.txt, doc/coc.txt, history.md, src/diagnostic/buffer.ts, src/diagnostic/manager.ts, src/diagnostic/util.ts, src/list/source/outline.ts
* Consistent formatting with things like `URI`, `API`, `<Plug>`, etc.
* Changed `list.source.outline.ctagsFilestypes` => `list.source.outline.ctagsFiletypes`
* Changed `diagnostic.highlighLimit` => `diagnostic.highlightLimit`
=> Fixed spelling mistakes and grammar in `docs/` and `data/schema.json`

data/schema.json, doc/coc-config.txt, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/buffer.ts, src/diagnostic/manager.ts, src/diagnostic/util.ts
=> feat(diagnostic): Support  "diagnostic.virtualTextLimitInOneLine"

src/list/basic.ts, typings/index.d.ts
Modify coclist PreviewOptions, allow coc auto detect the filetype of preview window if PreviewOptions.filetype was undefined.
=> modify coclist PreviewOptions & preview config

src/model/editInspect.ts
`Cannot read properties of undefined (reading 'label')`
=> fix(model): check empety annotations

README.md
I have fully converted the READMe config to lua, and this PR adds a new section showing the lua config.
=> Added full Lua config in Readme

src/model/chars.ts
=> fix(model): call Object hasOwnProperty

README.md
I wasted way too much time scouring over all my other plugins before realizing this was the problem. Hopefully I save someone else some sleep.
=> fix(README): correctly negate the conditional in Lua check_backspace

doc/coc.txt
Just reworded some sentences so they are a bit easier to follow where possible, also added some missing punctuation.
P.S. is it okay if I submit patches similar to this in the future?
=> Update the docs a bit

src/model/progress.ts
`token.onCancellationRequested` is not fired by clicking `Cancel` button when invoke `withProgress(_option, (_progress,  token) => {})`
Fixed by the pr
=> fix(progress): onCancellationRequested not fire

src/__tests__/modules/workspace.test.ts, src/core/documents.ts
=> fix(core): basename for workspaceFolder

src/provider/inlayHintManager.ts
`label: string | InlayHintLabelPart[]`
=> fix(inlayHint): label is string or InlayHintLabelPart[]

src/list/source/sources.ts
close https://github.com/neoclide/coc-sources/issues/64
=> fix(list): highlight source priory

src/provider/documentLinkManager.ts
The algorithm costs O(links^2) time but could be done using `Set` in roughly O(links) time.
The slow algorithm consumes 100% CPU for minutes when handling large files containing more than 14k (file) links in  https://github.com/NixOS/nixpkgs/blob/04e7308c6833a1f0a58dcdbd12309c7859f32d32/pkgs/top-level/all-packages.nix?raw=true
Note: Since `Set` uses `===` for comparison, we need to somehow serialize `Range`s into primitive strings. Not sure if there's a better approach.
=> fix(provider): optimize documentLink deduplication

src/language-client/features.ts
https://github.com/microsoft/vscode-languageserver-node/issues/1060
=> fix(language-client): documentSelector from capability should have higher priority

autoload/coc/pum.vim
Fix:
https://user-images.githubusercontent.com/17562139/211144607-cf25fe72-c0d9-4238-9373-a26d0d0e48d6.mp4
`<c-n>` shouldn't insert a new line. The current behavior is different from the built-in pum completion.
=> fix(pum): skip wrapping line if pum is visible

doc/coc.txt, plugin/coc.vim, src/handler/index.ts, src/plugin.ts
use current buffer if bufnr empty
=> feat(handler): hasProvider can accept bufnr

src/__tests__/handler/documentLinks.test.ts, src/handler/links.ts
=> feat(links): only fetch links on documeng changed

src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/buffer.ts, src/diagnostic/manager.ts, src/plugin.ts
=> feat(diagnostic): add target to diagnosticInfo

src/core/workspaceFolder.ts
=> fix(workspaceFolder): check directory of fsPath

src/handler/inlayHint/buffer.ts
Reduce flicker caused by inalyhint rendering during scrolling
=> chore(inlayHint): extend the rendering range a bit

src/list/session.ts
Fix https://github.com/neoclide/coc.nvim/issues/4555#issuecomment-1732504785
=> fix(list): `CocListResume` get wrong height

autoload/health/coc.vim
`health#xxx` functions have been deprecated, will be removed in 0.11
https://github.com/neovim/neovim/commit/c08b03076167837cff9eb66c19440d727e6dad31
=> refactor(health): use vim.health functions

data/schema.json, doc/coc-config.txt, doc/coc.txt, src/handler/symbols/index.ts
And also changed the docs in accordance to the new changes to cursorMove event
=> Allow configuration of the debounce time on current function setting

src/configuration/index.ts
fix invalid path on Windows
Closes https://github.com/fannheyward/coc-pyright/issues/1044
=> fix(configuration): join local coc-settings.json

autoload/coc/client.vim
=> fix(client): ignore -1 abnormal exit

src/handler/inlayHint/buffer.ts
same as content change debounce
related #4782
=> fix(handler): increase inlayHint render debounce

autoload/coc/util.vim, src/model/document.ts, src/types.ts
https://github.com/neovim/neovim/issues/27576
=> feat(model): use getbufinfo to check command line

src/handler/links.ts
=> fix(links): improve regex of link

src/handler/symbols/outline.ts
=> fix(symbols): close outline preview at closing

src/language-client/progressPart.ts
elm-language-server may returns `"percentage":100.00000000000155`
=> feat(language-client): round progress percentage

README.md, coc-example-config.lua, coc-example-config.vim
=> chore(docs): add coc-example-config in vim/lua

README.md, package-lock.json, package.json, src/__tests__/list/ui.test.ts, src/completion/complete.ts, src/completion/index.ts, src/diagnostic/buffer.ts, src/events.ts, src/extension/ui.ts, src/handler/format.ts, src/handler/highlights.ts, src/handler/index.ts, src/handler/signature.ts, src/list/manager.ts, src/list/session.ts, src/model/download.ts, src/model/fetch.ts, src/model/status.ts, src/tree/TreeView.ts, src/util/index.ts, src/util/timing.ts
`NodeJS.Timer` to `NodeJS.Timeout`
=> feat(package): @types/node@18

autoload/coc/util.vim
=> fix(util): timer to open file in vim

src/model/document.ts
=> fix(model): fetchContent without debounce time

src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/buffer.ts, src/diagnostic/util.ts
Closes https://github.com/fannheyward/coc-rust-analyzer/issues/1227
=> fix(diagnostic): stack hl groups

typings/index.d.ts
https://github.com/neoclide/coc.nvim/discussions/5053
=> feat(typings): more options in NvimFloatOptions

autoload/coc/pum.vim, doc/coc.txt
This commit add a function to check if there is a item selected in completion list.
Solve #5063.
=> feat(coc#pum#has_item_selected)

autoload/coc/util.vim, doc/coc.txt, history.md
=> feat(core): support NVIM_APPNAME

src/list/manager.ts, src/list/ui.ts
Reverts neoclide/coc.nvim#5098
=> Revert "feat(lsit): add CocListMoved autocmd"

autoload/coc/window.vim, src/handler/inlayHint/buffer.ts, src/handler/semanticTokens/buffer.ts
=> fix(handler): correct current winid

bin/prompt.js, src/model/quickpick.ts
Implements an alternate keybinding for coc-dialog-input toggle-selection as described in  #5184
=> Alternate keybinding for coc-dialog-input toggle-selection

doc/coc.txt
@fannheyward thank you for already merging #5187 
I just noticed that I forgot to update the help document.
=> update help for coc-dialog-input toggle-selection #5187

src/__tests__/modules/window.test.ts, src/core/highlights.ts, src/window.ts
checkMarkers is always true as coc.nvim needs nvim 0.8+
=> refactor(highlights): remove checkMarkers

history.md
=> chore(history.md): mentioned recently improvements

doc/coc.txt, history.md, src/handler/workspace.ts, src/plugin.ts
=> feat(scope): ensureDocument can accept bufnr

doc/coc-example-config.lua, doc/coc-example-config.vim
=> docs: correct coc-example-config url

doc/coc-api.txt, doc/coc.txt
=> chore(doc): typos

src/handler/index.ts
https://github.com/neoclide/coc.nvim/commit/7b3bae6457da2584b6ece5906b77973dbb0844a3
=> fix(handler): openSettingsJson command

src/commands.ts, src/completion/match.ts, src/configuration/configuration.ts, src/configuration/types.ts, src/language-client/callHierarchy.ts, src/language-client/configuration.ts, src/language-client/diagnostic.ts, src/language-client/features.ts, src/language-client/linkedEditingRange.ts, src/language-client/semanticTokens.ts, src/language-client/typeHierarchy.ts, src/language-client/utils/errorHandler.ts, src/model/db.ts, src/model/notification.ts, src/model/semanticTokensBuilder.ts, src/model/task.ts, src/provider/index.ts, src/tree/index.ts, src/util/array.ts, src/util/jsonRegistry.ts, src/util/lodash.ts, src/util/registry.ts
147286bde6d49767b8c02077759302cc593d6a9d
=> chore(comment): format comments

src/handler/index.ts
no need to check Unknown kind as we will use default one
=> fix(tree): remove Unknown checking

data/schema.json, history.md, src/handler/codeActions.ts
`coc.preferences.autoApplySingleQuickfix`
Related #5278
=> feat(codeActions): add autoApplySingleQuickfix

data/schema.json, history.md, src/__tests__/handler/inlayHint.test.ts, src/handler/inlayHint/buffer.ts
=> feat(inlayHint): add inlayHint.maximumLength option

autoload/coc/api.vim, src/__tests__/modules/util.test.ts, src/__tests__/snippets/parser.test.ts, src/configuration/registry.ts, src/language-client/diagnostic.ts, src/snippets/parser.ts, src/snippets/snippet.ts, src/util/diff.ts, src/util/textedit.ts, typings/index.d.ts
=> chore: typos

package-lock.json, package.json
all use jest 30 and reduce node_modules size
=> test(jest): upgrade @swc/jest

history.md, src/__tests__/list/sources.test.ts, src/core/notifications.ts, src/list/manager.ts, src/list/source/notifications.ts, src/window.ts
`:CocList notifications` cc @statiolake 
Closes #5375 
Only bellow notifications will be save to history for now
- `window.showInformationMessage`
- `window.showWarningMessage`
- `window.showErrorMessage`
=> feat(notifications): add notifications history

src/extension/manager.ts
This is a follow-up PR of #5380.
The activation order is still not considered on startup since extension.activate() is called directly..
This PR changes them to use manager.activate(id).
They are called asynchronously, so now we maintain `activating` as a parameter.
=> fix(extension): use activate(id) for all activation

src/plugin.ts
=> feat(notifications): add notificationHistory action

autoload/health/coc.vim
=> fix(health): warning on disabled on startup

autoload/health/coc.vim
=> fix(health): report error advises

plugin/coc.vim, src/attach.ts, src/core/dialogs.ts, src/events.ts, src/model/input.ts
=> fix(events): PromptExit to notify vim prompt exit

src/services.ts
=> feat(services): expand the cwd variable
