plugin/coc.vim, src/index.ts, src/model/document.ts, src/model/fileSystemWatcher.ts
This PR simply corrects the spelling of `initailize` to `initialize`.
=> Corrects spelling of "initailize" to "initialize"

src/source/file.ts
What I want: when entered `/` file trigger, items will popup for completion.
This maybe a **quick-but-dirty** fix, I just found that if `synName` is empty, `shouldComplete` will return false to disable completion. So I just add this check fix.
BTW, what's the effects of `synName string|comment` check?
=> fix file path completion

src/extensions/tsserver/features/bufferSyncSupport.ts, src/extensions/tsserver/features/fileConfigurationManager.ts, src/extensions/tsserver/utils/languageDescription.ts, src/extensions/tsserver/utils/languageModeIds.ts
In [b3604](https://github.com/neoclide/coc.nvim/commit/b3604e00d133e29777591349d352ae22b2c0015c#diff-375d26229ede96ca813dae07d7bdcf8a) prior to adding the typescriptreact type, it referenced 'typescript.jsx' not 'typescript.tsx'. I'm unsure of whether you intended for this, but it broke functionality for me.
If you'd prefer me to go through and rename all the variables to typescriptjsx or even add a new variable all together in all the necessary areas, I can do that for you, just let me know.
=> fix typescript.jsx languageModeId

autoload/coc/util.vim
Was seeing this trying to use yarn to install vim-node-rpc.
```
TERMINAL  yarn global add vim-node-rpc                                                                                                                                                                                                                                                           ☰    1  /4 ㏑
Error detected while processing function <SNR>88_OnExit:
line    6:
E118: Too many arguments for function: <SNR>88_rpc_installed
```
=> Fix too many args to rpc_installed

autoload/coc/rpc.vim, autoload/coc/util.vim
After restarting, the diagnostic info is not cleared, so that airline (and maybe other status lines) still shows the original error and warning number. However, the errors and warnings may be gone because of the new configuration of the language server. In these cases, the error and warning number in the status line will not be cleared until new errors or warnings appear.
=> Clear diagnostic info when restarting

plugin/coc.vim
I use `CocNvimInit` in my config. When I'm using coc in vim, this error will definitely occur:
```vim
Error detected while processing function <SNR>75_OnInit:                                                                                                
line    3:                                                                                                                                              
E117: Unknown function: dictwatcheradd                                                                                                                  
Press ENTER or type command to continue                                                                                                                 
```
Additionally, since this function is neovim specific, it's more robust to add …
=> Ensure call dictwatcheradd only in neovim

autoload/coc/util.vim
Currently the second invocation will fail because `OnExtensionInstalled` cannot be redefined.
=> Allows CocInstall to be run multiple times

data/schema.json, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/buffer.ts, src/diagnostic/manager.ts
solves #360
Adds: `"coc.preferences.diagnostic.virtualTextPrefix": " ",`
=> Allow configuration of virtual text diagnostic prefix

data/schema.json, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/buffer.ts, src/diagnostic/manager.ts
`coc.preferences.diagnostic.virtualTextLines`  allows the user to specify the number of non empty lines from each diagnostic message that should be shown in a single virtual text line.
`coc.preferences.diagnostic.virtualTextLineSeparator` allows the users to specify a custom `string` to go in between the conjoined lines.
This commit does not change any defaults, however I would advocate `virtualTextLines` defaulting to three instead of one. This would allow the standard `mismatched type\n {expected type}\n {found type}` diagnostics to be correctly displayed.
=> Config option to display multiple lines of a diagnostic in a single virtual text line

data/schema.json
A fix for an issue referenced in a [comment](https://github.com/neoclide/coc.nvim/issues/496#issuecomment-470785424) in #496.
=> fix(schema): add float as a valid value for hoverTarget

doc/coc.cnx, doc/coc.txt, plugin/coc.vim, src/diagnostic/manager.ts
My sign colunm background same as line number column. now the diagnostic float window background is same as the normal background. so it will be useful for float window has it's own highlight group different from sign column.
=> add float highlight

autoload/coc.vim
return empty string instead of a space when there is no diagnostic info.
=> trim coc#status()

install.sh
Yarn installs two binaries `yarn` & `yarnpkg`, currently the check only checks for `yarnpkg` only. I added the check for `yarn` two.
This will also match the node check which also check for two binaries `node` & `nodejs`
=> install.sh: Also check for yarn binary

src/source/file.ts
I have the following config:
```
'coc.source.file.ignoreHidden': false,
'coc.source.file.triggerCharacters': ['/', '.']
```
And, here is the file tree:
```
├── foo
   └── .bar
```
Input `foo/.b` will not suggest `.bar`, the PR fixed it.
=> fix(file): show hidden files completion

autoload/coc/util.vim
If `-m` isn't passed, shells which turn job control off when non-interactive (e.g. dash, the default sh on ubuntu) will error when installing coc. This PR fixes this issue by always turning on job control (via `-m`).
=> Turn on job control when installing

autoload/coc/util.vim
This is a requirement of the [language server spec](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#text-documents).
Inspired by prabirshrestha/vim-lsp#284
=> Ensure cursor position is counted by UTF16

install.cmd
If pwsh is loaded with user profile, and the user enables PSCX, Expand-Archive signature will be different.
=> install.cmd: use -NoProfile for powershell

data/schema.json, package.json, src/handler/index.ts, src/plugin.ts, yarn.lock
tl;dr
====
* New plugin action: `getCurrentFunctionSymbol`
* New preference: `coc.preferences.currentFunctionSymbolAutoUpdate`
* New depedency on `binary-search`.
---
A new handler method had been added (`getCurrentFunctionSymbol`) that
returns the name of the enclosing
Class/Method/Function/Interface/Enum/Constructor relative to the current
cursor position.
It will also set the `b:coc_current_function` buffer variable.
If the user choses to, by setting the
`coc.preferences.currentFunctionSymbolAutoUpdate` to `true` (default:
false), a hook is setup on the `CursorHold` event that will call
`getCurrentFunctionSymbol` and subsequently update the value of
`b:coc_current_function`.
This is useful in the context of an enhanced status line for instance.
Fixes …
=> feat(plugin): current function symbol

Readme.md, doc/coc.txt
Hey! I recently started using this plugin and am very happy with it! Since I was reading through the documentation anyways, I decided to make some small language-specific changes/improvements there.
I'm not a native english speaker so there might still be some problems with my changes but I think it's a bit easier to read the docs now. Let me know if I should undo any changes or if you have any other ideas.
=> Improve language in docs

doc/coc.txt
Hi !
There is a little error.
To make coc send diagnostics to alle we mast add : "coc.preferences.diagnostic.displayByAle": ***true***, and no false :-)
Thanks in advance
=> fix error doc/coc.txt faq ALE configuration

Readme.md
Scalameta Metals has been doing some amazing work and coc is currently the example they use with vim.
I've gone ahead and added the information in the Wiki, and then am linking it here.
=> Add in link to scala section in the wiki

Readme.md
Accidentally overwrote the Scala entry with last README update. This adds it back in.
=> add in scala reference

Readme.md
If you're in the Vim help, using `K` to move between blocks is also useful.
=> Use vim help for help files

package.json, yarn.lock
In relation to #738 
This feels like a better way to add dependencies that you need for building your plugin.
We still get the ability to run `npx npm-run-all clean build` from command line.
`yarn prepare` works as expected.
The dependency is clearly listed in `package.json`.
=> fix(yarn): add npm-run-all as devDependency

src/handler/index.ts
If coc.preferences.hoverTarget is set to echo:
Avoid request error if the current position is not on a valid 'hover
object'
=> Don't call coc#util#echo_hover without a valid message

Readme.md, doc/coc.txt
Mostly fixing typos and grammar.
Also, markup some more literals (identifiers, paths, package names).
And a couple of tweaks to phrasing.
=> Editing while reading: typos and grammar

doc/coc.cnx, doc/coc.txt, history.md
CocUpdateSync, obvious typo fix.
CocUninstall, fix capitalisation to match code.
=> Fix command names in docs (typo and capitalisation)

autoload/coc/util.vim
extension update should also ignore-scripts for VSCode-Only build scripts
=> chore(util): add --ignore-scripts on update command

autoload/health/coc.vim
Hi, I got this error, but `8.12.0` must be greater than `8.10.0`.
This regex works correctly.
=> fix regex for getting node version

plugin/coc.vim
This is would allow commands like `git.browserOpen` to open blocks of
code in github.
=> Allow ranges in `CocCommand`

autoload/coc/util.vim
我发现在此处传给 preview_info 函数的参数已经是一个列表了
[coc-git/src/manager.ts](https://github.com/neoclide/coc-git/blob/4b1105459a8691845fa746d29fad2b089f3cc529/src/manager.ts#L247):
```vim
this.nvim.call('coc#util#preview_info', [lines], true)
```
```vim
setl nofoldenable
let lines = split(a:info, "\n")
call append(0, lines)
exe "normal! z" . len(lines) . "\<cr>"
```
这里却又将其当作字符串
=> fix(util): preview failed to show chunkInfo in Vim8

Readme.md
The old link lead to a non existent wiki page
=> Fix the "Using configuration file" link

src/diagnostic/manager.ts
An off-by-one error relating to the `end_col` field passed to ALE was causing an extra character to be highlighted.
Latest build, using ALE:
Latest build, using coc native highlighting (ignore color differences and note the underline range):
This pull request, using ALE:
=> fix(diagnostic): correct ALE end column

autoload/coc/util.vim
When using coc-java with the latest coc.nvim, I found that URL with `jdt://` failed to load when using "Go to definition".
It turned out the `jdt://` URL contained special characters like `%` and `?` which needs escaping when used with `:edit`.
I think this bug is important to fix especially for coc-java users. coc-java interacts with such URL by nature like the following.
`jdt://contents/com.google.guava--guava--guava--jar--16.0.1.jar/com.google.common.collect/ImmutableList.class?=DummyProject/ide-lib%5C/compile%5C/com.google.guava--guava--guava--jar--16.0.1.jar%3Ccom.google.common.collect(ImmutableList.class`
=> fix(util): Escape filename for jump

Readme.md
There is an error from `sh` (i.e. `dash`) on Ubuntu 16.04 about `set -o pipefail` being unsupported
=> s/sh/bash/ in the 'nodejs' command

autoload/coc/util.vim
当调用 `:call coc#util#version()` 时
改动前
改动后
=> chore(util): tweak coc#util#version

src/handler/index.ts
I've tried the newest release of coc for golang and typescript. The function `getCurrentFunctionSymbol` works well in typescript but is broken in golang. After a while for digging, I found the DocumentSymbols response from typescript server is different from golang.
Specifically, the `range` and `selectionRange` property of `DocumentSymbol` response has a different meaning. Here's the definitions from [LSP specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol):
```
/**
* The range enclosing this symbol not including leading/trailing whitespace but everything else
* like comments. This information is typically used to determine if the clients cursor is
* inside the symbol to reveal in the symbol in the UI.
*/
range: Range;
/**
* The …
```
=> Fix comparing in getCurrentFunctionSymbol

Readme.md
For whatever  reason, the Github markdown parser seems to get confused when there's an HTML tag adjoining a markdown segment. The work around is a blank line between them. 
This fixes the link display in the paragraph about other completion engines.
=> Fix markdown link parsing

Readme.md
Its just a port of `vscode-elixir-ls` to coc.nvim, It uses internal language server. supports more features than raw language server installation using coc-settings
=> Add coc-elixir

data/schema.json, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/manager.ts, src/model/floatFactory.ts
This allow you to apply either the parent buffers filetype or an arbitrary file type to diagnostic floats.
=> Add config to set diagnostic filetype (syntax highlight diagnostics)

autoload/coc/util.vim, src/types.ts
Right now, in cygwin, the vim process will return via the `getpid()` command the cygwin pid. When trying to check that process from the node process (which is not a posix process) that will fail and after 15 minutes the coc.nvim is closed. 
Via this pull request, I am trying to get the winpid, instead of the cygwin pid. 
However, I was wondering what is the purpose of having the `workspace.ts::checkProcess` logic? The process launched via `job_start` in vim is a child process of vim. So, anyway, as soon as the vim process does not exists anymore, the node process will be killed automatically by the OS. This is valid for Linux, Mac and cygwin. I don't know for windows. But if this is not valid for windows, can we modify the function to be called only for Windows?
There is really no use for …
=> Added support for cygwin

src/__tests__/modules/workspace.test.ts, src/handler/index.ts, src/list/source/folders.ts, src/workspace.ts
Vim prompts generally are formatted with a leading capital letter and space. For example, the prompt when pressing `%` in netrw to create a new file:
coc.nvim uses a lowercase first letter and no trailing space:
This change updates the text formatting to be more similar:
=> style: Clean up input text formatting

autoload/coc/rpc.vim, autoload/coc/util.vim, doc/coc.txt, src/extensions.ts, src/workspace.ts
This is something that has been asked about in the past - one example (https://github.com/neoclide/coc.nvim/issues/718)
This helps improve maintenance of dotfiles for both vim and neovim. It allows for a way to use coc.nvim with neovim without needing to add a symbolic link somewhere to to .config. Everything is configurable from within the vimrc.
Let me know your thoughts.
=> Allow coc_config_home to be configurable

src/util/complete.ts
Haskell and many other functional languages don't use parentheses or any other symbol to denote calling.
=> Fix completion for Haskell

autoload/coc/api.vim
After repeated calls the `buffer.addHighlight` and `buffer.clearNamespace`, cached will very large, causing `clearNamespace` too slow.
=> fix(api.vim): clear highlight namespace cached

autoload/coc/api.vim
Test demo
```typescript
import { workspace } from "coc.nvim";
export async function activate() {
const { nvim } = workspace;
workspace.registerKeymap(["n"], "storeCursor", () => {
async function test() {
const winid = await nvim.call("win_getid", []);
const win = nvim.createWindow(winid);
const [line, col] = await win.cursor;
win.setCursor([line, col]);
workspace.showMessage([line, col].join(","));
}
test();
});
nvim.command("nmap gs <Plug>(coc-storeCursor)");
}
```
=> fix(api.vim): nvim_win_get_cursor() col index start from 0

src/model/fetch.ts
Fixes #1186.
When length of `noProxyHost`/`noProxyItem` is one char longer than `hostname`, proxy becomes null even if hostname does not matches noProxy patterns.
=> fix(fetch): fixes #1186

src/diagnostic/manager.ts
1. `diagnostic.refreshOnInsertMode` should work when `diagnostic.displayByAle == true`
2. `diagnostic.refreshOnInsertMode` should work when `diagnostics.length == 0`
=> fix: diagnostic.refreshOnInsertMode

src/list/source/outline.ts
Vetur lsp server doesn't provide uri for 'stylus' locations.
I think it should be fixed on the server's side, but in order to not break user's experience because of missing uri in Location, we can restore uri on client's side.
=> fix(outline): adds uri to location if it's undefined.

plugin/coc.vim
#1276 
I have made changes to `CocFloating` highlight only for neovim, because i believe that vim doesn't have `NormalFloat` highlight group.
=> Link CocFloating to NormalFloat in neovim

src/handler/refactor.ts
This PR fixes the usage of `documentChanges`. Previously `if (!changes)` could never be true because right in the line before `changes` is initialized with `{}` as a fallback.
This - at least for me - broke the php language server.
=> Fixes the usage of documentChanges

src/diagnostic/manager.ts
With coc-python extension, pylint and flake8 enabled and `displayByAle` is on, say we have this file:
``` python
def foo():
print('foo')
def bar():
print('bar')
var = baz
```
Then there are error messages:
```
test.py|4 col 1 error| [python] E302: expected 2 blank lines, found 1
test.py|8 col 7 error| [python] F821: undefined name 'baz'
test.py|8 col 7 error| [python] E0602: Undefined variable 'baz' (undefined-variable)
```
Note that they all have `[python]` header. This patch changes this to:
```
test.py|4 col 1 error| [flake8] E302: expected 2 blank lines, found 1
test.py|8 col 7 error| [flake8] F821: undefined name 'baz'
test.py|8 col 7 error| [pylint] E0602: Undefined variable 'baz' (undefined-variable)
```
And this behavior is more similar to ALE's one.
=> feat(diagnostic): classify ALE items by their source

plugin/coc.vim
Found a typo in the `coc-range-select-backward` definition. Note the doc contains the correct spelling: https://github.com/neoclide/coc.nvim/blob/77695b071afc78bfa4eea322b746c0ec308f221a/doc/coc.txt#L774
Thanks for the great software.
=> Fix typo in coc-range-select-backward

src/handler/index.ts
This fixes #1372 
on_enter not working correctly when using VIM
=> fix(on_enter): document not synced when using VIM

autoload/coc/util.vim
I came across this when working on a feature for [coc-metals](https://github.com/ckipp01/coc-metals) where I wanted a quick way to pass some text to a temporary preview window, and then just throw it away.
I found `coc#util#preview_info` to be exactly what I needed, but I just wanted a couple of other things to be set. For example, I wanted a `setl nonumber` to also be set. I played around with just making another call to do this when I realized that `coc#util#preview_info` is only used twice in the code base, and each time the `filetype` is passed in, so there is really no need for it to be a varargs. So if we just make filetype explicit, and then make the varargs a list of commands that we want to be executed, it will allow for the function to be used with some additional setting passed …
=> change util function to be more explicit and also extendable

src/util/index.ts, src/workspace.ts
```typescript
import { workspace } from "coc.nvim";
export async function activate() {
const { nvim } = workspace;
workspace.registerKeymap(["n", "v"], "echoline", async () => {
const [line, count] = (await nvim.eval("[line('.'), v:count]")) as [
number,
number
];
workspace.showMessage(`line: ${line}, count: ${count}`);
});
nvim.command("map gl <Plug>(coc-echoline)");
}
```
1. Open buffer
2. type `3gl`
Before patch:
```
[coc.nvim] line: 1, count: 3
[coc.nvim] line: 2, count: 3  -> When I was on the second call, I can't get the correct line number
[coc.nvim] line: 3, count: 3
```
After patch:
```
[coc.nvim] line: 1, count: 3
```
https://github.com/weirongxu/coc-explorer/issues/56
=> fix(workspace): fix error line number under duplicate call with count prefix

data/schema.json, doc/coc.txt, src/workspace.ts
`.vim` folder is always in $HOME, used as default pattern will always resolved `$HOME` to rootPath
=> feat(workspace): rm .vim from default rootPatterns

src/util/fs.ts
Part of the implementation of yarn's new PnP feature (https://yarnpkg.com/en/docs/pnp/getting-started) is that project dependencies are stored in .zip archives. When coc-nvim tries to read one of those files (for example, during a "goto definition" jump), the `createReadStream` function throws an exception which currently causes Vim to hang completely.
With this change, coc-nvim checks if the file exists before attempting to read it, preventing the thrown exception and preventing Vim from hanging when jumping to a definition located in a PnP module.
There is still an error visible in the UI (the "file does not exist: ...." error), but in this case it doesn't hang the UI completely
=> Add a check if a file exists before attempting to read it

plugin/coc.vim, src/plugin.ts
I think it's valuable to have a function to easily return the current buffer workspace path.
This makes it easier to make mappings to run/build projects by reusing functionality Coc already has.
=> CocCurrentWorkspacePath returns workspace path

src/list/source/outline.ts
The outline coc list is not quite that useful (at least for me) if I cannot filter also by kind. 
What I want to do is this:
`CocList --normal --no-sort --input=Method outline -kind` and see only the methods form the current file, which in a lot of cases will be the current class. 
Then I can even press `i` and add a method name in input (for example `Method doHighlight`) and find my method.
The issue for me is that sometimes I don't know the method name, so I want to have a class outline. Hope this clarifies. 
The option by default is false, which means that the behavior is the current one.
=> Added option to include the kind in filtering the outline

autoload/coc/util.vim
I set `"coc.source.{buffer,around}.disableSyntaxes"` to suppress unwanted completion, but it doesn't seem to working.
I found it is because here the conditional expression `!synname` is nonsense, since Vim script converts `synname` from string to number before the `!` operation. (`:help expr7`)
`synIDattr()` seems to return empty string if no info was found, so the three lines can simply be removed.
neoclide/coc-sources#21 may be related.
=> Fix "coc.source.*.disableSyntaxes" not working

data/schema.json, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/manager.ts
Highlights numbers with the same style as the previous signs; this eliminates the need for the signcolumn if you don't want it, i.e. numbers are red for errors and yellow/brown for warnings.
=> adding number highlighting

src/language-client/index.ts
I tried setting some custom environment for my LSP using the following config:
```js
"languageserver": {
"golang": {
"command": "gopls",
"rootPatterns": ["go.mod"],
"filetypes": ["go"],
"env": {
"GOFLAGS": "-tags=endtoend"
}
}
}
```
However the language server fails to start as `options.env` is not extensible.
Output from CocInfo:
```
vim version: NVIM v0.4.3
node version: v13.5.0
coc.nvim version: 0.0.74-6700e7468d
term: screen-256color
platform: linux
[coc.nvim] Server golang failed to start: Cannot add property AP, object is not extensible
[Error  - 3:58:46 pm] Starting client failed:
TypeError: Cannot add property AP, object is not extensible
at Function.assign (<anonymous>)
at LanguageClient.createMessageTransports (/home/brendan/.local/share/nvim/plugged/coc.nvim/build/index.js:54315 …
```
=> fix object not extensible error when supplying env as part of LSP config

data/schema.json, doc/coc.txt, src/handler/index.ts
This will only take effect when `coc.preferences.formatOnType` is `true`, and will only check this setting when not empty, in order to avoid breaking change.
close #1472
=> feat(handler): formatOnTypeFiletypes support

src/snippets/parser.ts
- Keep inner indent of variables
- Keep empty line empty
Still known issues:
- If first line is empty, it will still be indented
- Mixing tab and space may cause unexpected result
For example, suppose we have a snippet
```ultisnips
snippet forever "forever loop"
while (true) {
${VISUAL}
}
endsnippet
```
and code
```c
int main() {
if (cond) {
// aa
// bb
}
return 0;
}
```
Now we select the `if` statement and expand the snippet (with coc-snippets), with current implement, we would get
```c
int main() {
while (true) {
if (cond) {
// aa
// bb
}
}
return 0;
}
```
but what we want is
```c
int main() {
while (true) {
if (cond) {
// aa
// bb
}
}
return 0;
}
```
=> feat(snippets): fix multiple lines variable indent

autoload/coc/rpc.vim, autoload/coc/util.vim, doc/coc.cnx, doc/coc.txt, jest.js, src/model/mru.ts
used for coc data files location.
close #1528
=> feat(util): add g:coc_data_home

src/list/source/commands.ts
It's useful for input arguments
=> feat(source): add append action for commands source

src/util/factory.ts
Fixes: #1540
Some extensions are calling console.debug (for instance coc-metals through metals-languageclient) which is normally available on the NodeJS console object.
=> fix(extensions): add console.debug to extension sandbox

data/schema.json, doc/coc.txt, src/__tests__/modules/diagnosticManager.test.ts, src/diagnostic/manager.ts
When checkCurrentLine is enabled but there are diagnostics exactly under the
cursor, only show those. If there are none, show all diagnostics from the line.
That way it's still easy to inspect diagnostics with small ranges, but
it's possible to distinguish when there's several diagnostics on a line.
=> feat(diagnostic): checkCurrentLine is a fallback behavior

src/__tests__/modules/completion.test.ts, src/completion/complete.ts, src/languages.ts
Client-side filtering and ranking of LSP results is great for latency,
but can't take into account server-side signals such as popularity,
type-matches-context etc.
This extension lets the server provide a numeric score multiplier.
It's documented here: https://clangd.github.io/extensions.html
clangd implements it at trunk and in the pending 10.0 release.
This is the main blocker for recommending coc.nvim for clangd. (currently we
recommend YCM and just turn all client-side filtering off).
https://github.com/clangd/clangd/issues/284
My attempt to get something like this standardized doesn't seem to be moving:
https://github.com/microsoft/language-server-protocol/issues/348
=> feat(completion) support `score` extension on LSP CompletionItem

src/language-client/client.ts, src/languages.ts
LSP says if commitCharacters is not provided for a particular completion option,
CompletionOptions.allCommitCharacters should be used instead.
=> fix(completion): support allCommitCharacters as fallback for commitCharacters

src/model/floatBuffer.ts
Previously the active ranges would "accumulate" as signature help proceeded:
```
int foo(int x, int y, int z);
int a = foo(    // "int x" is shown active
int a = foo(1,  // "int x, int y" is shown active
int a = foo(1,2,// "int x, int y, int z" is shown active
```
This is because the highlight matches weren't being properly cleared.
I'm not sure exactly why win_execute doesn't work, but the fact that the
clearmatches([win]) variant exists hints there's some problem here :-)
Verified bug+fix with vim+nvim and clangd.
=> fix(signature): clear old active range highlight in floatBuffer when reusing

package.json
`node_modules/.bin/jest` is a sh script. Therefore it only runs on *nix systems. When run on Windows, a syntax error is thrown.
I have found a [reference](https://github.com/facebook/jest/issues/3750) to this issue.
The changed scripts have been tested on windows. Although some tests failed, jest was working as expected.
=> fixed test script

src/__tests__/modules/completion.test.ts, src/completion/complete.ts, src/languages.ts, src/types.ts
PR #1559 adds score from LS to CompletionItem, but coc will compute `item.score` as user types, so we can't use `item.score` to save score from LS.
=> fix(completion): add sourceScore for CompletionItem

src/source/file.ts
Often in my work day, I use paths which feature an env variables like: `$REPO_ROOT/foo/bar`
Until now, the filename completion was not working as env variables were not resolved.
This PR implement env variables resolution for filename both on Windows and Linux/Mac.
I tested it on my end and it seems to be working fine.
What do you think?
Thanks,
Antoine
=> feat(file): resolve environment variables in filename completion

data/schema.json, package.json, src/__tests__/client/server/testInitializeResult.js, src/cursors/index.ts, src/handler/colors.ts, src/handler/refactor.ts, src/language-client/client.ts, src/language-client/colorProvider.ts, src/language-client/declaration.ts, src/language-client/foldingRange.ts, src/language-client/implementation.ts, src/language-client/index.ts, src/language-client/progress.ts, src/language-client/progressPart.ts, src/language-client/selectionRange.ts, src/language-client/typeDefinition.ts, src/language-client/utils/converter.ts, src/language-client/workspaceFolders.ts, src/services.ts, src/snippets/session.ts, src/types.ts, tslint.json, yarn.lock
This PR will upgrade `vscode-languageserver-protocol` to 3.15, and port `vscode-languageclient` 6.1.1 to language-client.
I've tested with gopls/rust-analyzer by `languageserver`, and coc-tsserver/coc-json/coc-rust-analyzer/coc-clangd extensions, everything works as expect. More tests from extensions are needed, @iamcco @weirongxu @voldikss @oblitum @yatli and everyone else, hope you guys can help.
~TODO: progress support is done in language-client, but not on coc side, WIP.~ Done, basic progress just shows on status line. I'll open another PR to add custom progress report support.
=> Upgrade to LSP 3.15 and port vscode-languageclient 6.1.1 to language-client

src/workspace.ts
Not sure whether PRs for settings like this are appreciated, but this is driving me a little nuts, I don't think it's the right default.
Output windows open in a vsplit (so often narrow) and having logs wrap is annoying:
- it hides the typical repetetive structure that makes logs easy to
visually scan
- in the presence of very long lines (which are reasonably common) you
often see only a couple of log entries, and half the screen is blank
Current:
(Note half the window is displaying nothing, though there are more logs, because the next line is very long)
Patched:
=> fix(outputChannel): don't wrap in log files

src/model/floatFactory.ts
Currently if a float for diagnostics always triggers to the right
of the cursor. This is fine when the cursor is near column 0, but the right edge
of the window limits the size, so if the cursor is at say 70/80, there
are only 10 columns available and the content wraps *a lot*.
Compounding this, maxheight is set to number of lines of content, but
isn't increased if the content has to wrap. So when the content
wraps, it's truncated. (Scrollable, but this is awkward)
Current:
Patched:
Looking at the history, it seems there's been some tension between
wrapping and fixing widths. 77cbc92ca5c38e1be moved the window to the
left if there wasn't enough room (so it wouldn't wrap), but then
46e0f4d8e5d90ed42 made it conditional on offsetX != 0, which meant
everything except signature help wraps …
=> fix(float): stop floats from getting too small on the RHS of the screen.

data/schema.json, src/completion/complete.ts
I've currently experienced some issues with `rust-analyzer` taking longer than default 5s, and I seem to not be the only one. Reference below,
https://gitter.im/neoclide/coc.nvim?at=5e0acd6c833c373f4d84eae4
PR increases the max timeout to 15s without touching default. PR also sets the correct minimum value.
=> increase max timeout to 15000

src/language-client/progressPart.ts
When showing job progression in the text editors, it is hard to read
"precise" percentage numbers. This patch sets precision of
`WorkDoneProgressBegin.percentage` to 2 decimal places to improve
readability.
=> Set WorkDoneProgressBegin.percentage precision to 2 decimal places

src/completion/complete.ts
With `"suggest.removeDuplicateItems"` set to `false`, I can get both `#include <` and `#include "` when I use ccls for cpp completion.
After setting that option to `true`, I only got `#include "` and `#include <` was removed.
That is unreasonable. Though these two items share the same label(`'include'`), but they apply different `textEdit`(`'include <' v.s. 'include \"'`). Therefor the second one should be preserved.
According to the code comment [here](https://github.com/neoclide/coc.nvim/blob/master/src/types.ts#L497),  we can check if the item will apply a textEdit before removing it.
=> fix(completion): preserve duplicate items for textEdit

src/handler/index.ts
do not add `line 1` of destination file to the jumplist
=> fix(plugin): keepjumps for CocTagFunc

autoload/coc/util.vim
This is used for workspace/showMessage, when it contains multiple lines.
Using `echomsg` in a loop means that each line after the second prompts
before displaying.
The downside of this change is if there are multiple consecutive calls
to `echo_messages()`, only the last one is shown. (All will appear in :messages)
Motivating use: clangd has "dump AST" code action behind the
-hidden-features flag. This action calls showMessage with a payload like:
```
FunctionDecl 0x14387ee101e8 </home/sammccall/test.cc:1:1, line:3:1> line:1:6 foo 'void ()'
`-CompoundStmt 0x14387ee10380 <col:11, line:3:1>
`-DeclStmt 0x14387ee10368 <line:2:3, col:10>
`-VarDecl 0x14387ee10300 <col:3, col:7> col:7 bar 'int'
```
=> fix(util): suppress 'press ENTER' in echo_messages()

src/extensions.ts, src/model/document.ts
As I tried to transplant a [vscode plugin](https://github.com/mdx-js/vscode-mdx), activationEvents does not trigger on opening mdx files.
mdx is not a built-in filetype of vscode language server at the moment.
The [contributes.languages](https://code.visualstudio.com/api/references/contribution-points#contributes.languages) feature of allows vscode extensions to define their own filetype, i.e. extensions mapped to language identifier. Therefore vscode-mdx works fine without the official support of mdx filetype from vscode.
However coc.nvim is lack of this feature at the moment.
I will eventually try to implement this feature. But I wish to focus on the original problem, which is to transplant vscode-mdx to coc. So a dirty and temporary workaround is made.
The change has been kept minimal. …
=> added mdx filetype identifier

src/diagnostic/manager.ts
As discussed at https://github.com/fannheyward/coc-rust-analyzer/issues/174, we can separate `diagnostic.relatedInfomation` as diagnostics to help users for coding.
Added an option `diagnostic.separateRelatedInformationAsDiagnostic` to control this feature, default `false`.
=> feat(diagnostic): separate related information as diagnostics

doc/coc.txt
The docs were inaccurate; the configuration filename `coc-config.json` is invalid. I spent a bit of time scratching my head while reading the vim docs until I read `README.md` and saw that the local config file is actually `coc-settings.json`.
As always, thanks for this amazing plugin / Neovim ecosystem!
=> Remove references to `coc-config` in English docs

src/services.ts
`client` is missing with `services.registLanguageClient(client)`, then will failed on `registNotification` at https://github.com/neoclide/coc.nvim/blob/master/src/services.ts#L201
=> fix(services): missing client

autoload/coc/api.vim
`nvim_buf_set_lines` will keep the view and cursor.
=> fix: buf_set_lines should keep view and cursor on vim

src/languages.ts
getStartColumn only checks first 10 items, others maybe contain empty
textEdit.
close https://github.com/fannheyward/coc-texlab/issues/143
=> fix(languages): check textEdit null

src/list/prompt.ts
This is a _**quick-dirty**_ fix to make tests passed. From https://github.com/sindresorhus/clipboardy/issues/57#issuecomment-562033847 and my local tests, clipboardy fails on ubuntu and will block tests to run.
=> test(list): fix failed paste on ubuntu

src/language-client/client.ts
If separateRelatedInformationAsDiagnostics is enabled, coc.nvim doesn't
update the diagnostics when the list of diagnostics is empty.
This PR fixes this bug.
=> fix(diagnostic): don't miss updating the diagnostic list if diagnostics empty

src/workspace.ts
Looks like a regression to #225, re-introduced in
7eb2d4c00599a7f82e1e50c62ec5767be8e9605c?
I noticed the issue while using ocaml-lsp locally.
=> workspace: handle version=0 in rename validation

src/handler/index.ts
Fixes neoclide/coc-java#80
This fixes the handling of tagList filename for the cases where the scheme of the definition returned by the language server is not 'file' ( example : Libary functions of java which return definitions with 'jdt' scheme).  
While this seems to fix all of the cases I have encountered, a more robust method of sending final URI might be needed similar to what's done in coc#util#jump() for some cases.
=> fix( getTagList): handle filename for urls with non-file schemes  

src/list/source/extensions.ts
`:CocList extensions` - `Tab` will list extension actions, but `doc` action is missing, and actions after `doc` will return wrong choose number.
=> fix(extensions): doc action is missing

src/handler/index.ts
It is a Language Server's job to correctly handle signatureHelp. coc.nvim should not attempt to fix buggy language servers on the client side because this will break non-buggy language servers.
Resolves https://github.com/neoclide/coc.nvim/issues/1467
Note: this resolves the issue by removing something some people may arguably consider a feature (I view it as a bug, but others may disagree with me). An alternative would be to keep this bug, add a documented option to disable it, and modify the code accordingly. I'm submitting this PR just in case you, like me, prefer to simply eliminate this bug-inducing code.
=> Stop modifying position of cursor on signatureHelp

plugin/coc.vim, src/handler/index.ts, src/plugin.ts
Creates pluggable mappings for class text objects. Also, generalizes the function code to make it generally applicable to any DocumentSymbol range.
Topic for discussion: should we consider `['Interface', 'Struct', 'Class']` as all part of a "class" text object? I think about them similarly across languages, so I'm inclined to say yes.
I'll update the English docs if you generally approve of this PR / once we agree on the implementation.
=> Create pluggable mappings for classes: <Plug>(coc-classobj-*)

README.md, doc/coc.txt
There are no default mappings provided by either funcobj-* or
classobj-*. Instead, there are Coc-recommended keys / modes to which
these pluggable mappings should be mapped.
See here for reference: https://github.com/neoclide/coc.nvim/pull/1875#issuecomment-626221554
=> Clarify funcobj and classobj: no default mappings

src/services.ts, src/types.ts
LanguageServerConfig.enable was mistyped and the linter got it wrong.
There's a chance this is happening in other places, I'd recommend
reviewing all changes from `!== false` or `=== false` to simple truthy
checks. Avoiding boolean values that default to true would make the
code easier to reason about too.
Related to #1878 and #1881.
=> services: fix config check in process start

plugin/coc.vim, src/handler/index.ts, src/plugin.ts
By exposing `selectSymbolRange` instead of `selectClass` and `selectFunction` (which I've removed), end users can write their own pluggable mappings while maintaining the same public interface in Vim / Neovim.
Ultimately, this PR gives the end user more configuration control while maintaining existing mappings / not changing any important public interfaces.
=> select[Function,Class] changed to selectSymbolRange

data/schema.json, doc/coc.txt, src/handler/codelens.ts
Added sub-separator between codelenses in virtual text in case there are multiple codelenses at one line.
The motivation is that [`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer) returns CodeLens item whose title includes space character like `Run Bench`. If it appears with other CodeLenses, virtual text becomes confusing.
So I added `codeLens.subseparator` option. 
If `codeLens.subseparator: " | "`, virtual text in same case as above is displayed as below:
(If `codeLens.subseparator: " "`, behaves as before)
=> Add subseparator between codelenses in virtual text

src/model/floatFactory.ts
When document is empty height will get a `NaN`, 
`(w - 2) / (width - 2) = 0 / 0 = NaN`
https://github.com/neoclide/coc.nvim/blob/d3d460db324093fa3af674243538590708792ef1/src/model/floatBuffer.ts#L182
=> fix: avoid height is NaN, fix #1934

src/extensions.ts
if `uri` is `null`, all my coc extensions won't be loaded. 
Firstly mentioned by @willfish here https://github.com/neoclide/coc.nvim/commit/d7b30843755d6040f46d9d7d2fbc8f49fc366e1c#r39264105
=> fix(extensions): fix can not load extensions if uri is null

doc/coc.cnx
Replace "模块" with "模式".
Signed-off-by: Ding Tao <i@dingtao.org>
=> doc: Fix a simple typo in file coc.cnx

doc/coc.txt
Documentation indicates a `"suggest.enablePreselect"` default value of `true`, whereas the code and the schema indicates `false`
This PR modifies the value in documentation in order to reflect the code
=> docs(configuration): Fix obsolete default value

data/schema.json, doc/coc.txt, src/handler/index.ts
This is the fixed version of #1946. Apparently I mixed up the "preview" window and the hover/popup window used for completion "preview".
This is a configuration to limit the max height of a preview window used for hover. Only valid when `coc.preferences.hoverTarget` is `"preview"`.
=> add coc.preferences.previewMaxHeight

README.md
This snippet does not work as is, and is missing the top level key for the language.
=> Fix example language server config in README

src/model/floatBuffer.ts
This reverts commit 915af62ce70cef1dffe04dc63a44763d9706fec7.
On environments that East-Asian `Ambiguous characters are double-width`[1],
`\u2500` is treated as a double width character, and 
horizontal line in popup will be drawn bad like below screenshot.
(Screenshot on iTerm2, macOS)
`-` is treated as a single width character anytime, so it will be drawn good.
[1] UAX # 11: East Asian Width http://www.unicode.org/reports/tr11/tr11-38.html
=> Fix drawing horizontal line on CJK

data/schema.json, src/list/ui.ts
This adds a function called calculate height to the list ui.
It adds a config option in schema.json for minimum height.
It changes the default value, if not in config, for maxHeight to match default given in schema.json
I did not see any tests on the UI portion, but if I missed that and you want tests for this, I will add them.
=> Add option for list minimum height.

autoload/coc/util.vim, autoload/health/coc.vim, plugin/coc.vim
Pretty straight forward amendment here to allow node's path to be set via an environment variable.  One use case, of many, is when it is desirable to spin up a new work environment with neovim + coc.  coc's node path dependency can now be preconfigured without parsing / writing configuration files.  This code change allows one to still override the env variable with `g:coc_node_path` and as a last fallback still use `node`.
=> feat(env): allow nodejs path to be set by the environment

src/model/installBuffer.ts
Stay in current buffer, with `q` to close directly.
=> feat: stay in current buffer when CocUpdate

src/commands.ts
This command would be the equivalent of  Shift+F7 in VSCode.
And the opposite of document.jumpToNextSymbol.
Please see #1290
=> add document.jumpToPrevSymbol command

src/languages.ts
Coc should remove the candidate when insertText is empty.
https://github.com/fannheyward/coc-docthis/blob/ecadbce31ec5ea673e5627df7ef07ac2178ad4ce/src/index.ts#L41
=> fix: when insertText is empty

doc/coc.txt
Should say `hint diagnostics` instead of `info diagnostics`. Fairly small fix.
=> docs: Fixing wrong word for hint in docs

src/util/fs.ts
`os.homedir()` get the uppercase disk symbol `C:`, but dir is lowercase
=> fix: resolveRoot in windows

plugin/coc.vim
It shows on CursorMoved autocmd especially, here are profiling results:
- 1295   0.918150   0.122849  <SNR>40_Autocmd() (before)
- 1289   0.821687   0.092443  <SNR>40_Autocmd() (after)
It aint much, but it's honest work.
=> perf(autocmd): remove calls to get() for 15% faster autcmd

data/schema.json, doc/coc.txt, src/language-client/client.ts, src/services.ts, src/types.ts
Continue of #280
Motivation: I want my custom language server have higher format priority than the coc-tsserer
=> feat(language-client): support config formatterPriority

src/handler/index.ts
Closes #2266.
Simply adds the kind 'Struct' to the list of kinds to filter by when obtaining the current function symbol. Structs are the same thing as classes in C++, so they should be recognized here along with the 'Class' kind.
=> Allow structs when filtering current function symbol

src/list/manager.ts, src/plugin.ts
Retrieve list info to process it using FZF for instance.
Avoids having 1 CocAction per list (e.g.: commandList, diagnosticList etc)
This is a POC, please let me know if anything needs to be changed.
This would help me support way more lists in coc-fzf :smiley:
=> feat: add CocAction('listLoadItems', 'list_name')

autoload/coc/terminal.vim, autoload/coc/util.vim, src/workspace.ts
Whenever Coc does `doautocmd` vim triggers processing of modelines. This might be quite annoying if the modeline includes something like `foldlevel=0`. I believe most of Coc's user autocmds do not need to trigger modelines processing. In such cases, [`:h <nomodeline>`](https://neovim.io/doc/user/autocmd.html#%3Cnomodeline%3E) can be used.
I left out this one since it is probably correct to process modelines in this case.
https://github.com/neoclide/coc.nvim/blob/c8d43d990593e2184da1dcb55870faa19082415e/autoload/coc/util.vim#L1180
ref #452
=> <nomodeline> for User autocmds

README.md
I wrote this article because I struggled a bit writing my first coc
extension to wrap an executable language server. The article provides
both the reason and the method to write a coc.nvim extension.
Additionally, it goes over why coc.nvim is different from other nvim LSP
clients and how it relates to vscode. My hope is that it makes it easier
for other developers to write coc extensions so that we get more of
them.
=> Add link to my detailed article on coc extensions

doc/coc.txt, src/commands.ts
While working with `coc.preferences.formatOnSaveFiletypes` and looking through some of the issues, I found that the suggestion was to run `echo &filetype` to determine the correct filetype to be adding to the array of this configuration option. This is not exactly correct because as the documentation states, `coc.nvim` will map certain filetypes to others under the hood, and it is actually this mapped filetype that is used to determine if the formatter should be run ([src](https://github.com/neoclide/coc.nvim/blob/634810782446f9166b1924c64d249e5092f7467a/src/languages.ts#L109), [src](https://github.com/neoclide/coc.nvim/blob/fd9e7d3972a5300da2acf648c2f5f23d1983c111/src/model/source-vim.ts#L52)). Adding a utility function that can be called by a user to determine the filetype as understood …
=> Add utility to find the filetype as understood by coc

plugin/coc.vim
```
E119: Not enough arguments for function: coc#rpc#notify
```
=> fix: CocOpenLog

plugin/coc.vim
<afile> in DidChanged is not always correct.
fix weirongxu/coc-explorer#267
1. vimrc:
```vim
set nocompatible
autocmd DirChanged * echom expand('<afile>')
autocmd VimEnter * chdir /home/raidou
filetype plugin indent on
syntax on
set hidden
```
2. Open vim from `/` root directory:
```
cd /
vim -u path/to/vimrc
```
3. cd to subdirectory inside the `/home/raidou`
```vim
:cd repos/
```
Vim will print `repos/`
=> fix: cwd DirChanged on vim

src/diagnostic/manager.ts
Before this, diagnostic message will be popup after switching buffers even if I didn't press `<Plug>(coc-diagnostic-next/prev)`.
=> Show diagnostic message only if <Plug>(coc-diagnostic-next/prev) pressed

src/workspace.ts
default height of `copen` is 10, if the items are less than 10,
we should set height manually to make the behavior like default coclist's.
=> fix: adjust copen height when enable useQuickfixForLocations

autoload/coc/util.vim
`coc#util#float_scroll_i(amount)` allows scrolling floating windows in NeoVim
without exiting insert mode, by a given `amount` of lines.
Example usage:
```vim
let g:coc_snippet_next = '<c-l>'
let g:coc_snippet_prev = '<c-h>'
inoremap <silent><expr> <c-j> coc#util#has_float() ? coc#util#float_scroll_i( 1) : "\<c-j>"
inoremap <silent><expr> <c-k> coc#util#has_float() ? coc#util#float_scroll_i(-1) : "\<c-k>"
vnoremap <silent><expr> <c-j> coc#util#has_float() ? coc#util#float_scroll_i( 1) : "\<c-j>"
vnoremap <silent><expr> <c-k> coc#util#has_float() ? coc#util#float_scroll_i(-1) : "\<c-k>"
```
With this configuration one can scroll with `<c-j>`/`<c-k>` (vertical keys) and
jump snippet placeholders with `<c-l>`/`<c-h>` (horizontal keys).
Give it a try, it's quite useful! :)
=> Add insert mode float scrolling function

data/schema.json, src/model/fetch.ts
Hi, 
I see that if you are using COC through a SSL-inspection proxy your only choice is to disable SSL verification with `http.proxyStrictSSL = false`,
This PR adds the support to read a certificate authority file, with the option `http.proxyCA = "filename"`which you can use to trust the certificates signed by the proxy.
best regards,
Fredrik
=> http.proxyCA support 

src/handler/index.ts
Use manual fold such as '<,'>fold will close this fold at first time,
although the current foldlevel is 99, we should use `zx` to re-apply
fold to make fold obey foldlevel.
BTW, zx seems that enable fold automatically, foldenable is unnecessary.
=> fix: foldlevel doesn't work after processing fold

README.md
modified show_documentation function so the default behaviour of K would not get overridden when coc#rpc is not available.
In the example vimrc configs in README.md, the default behaviour of K was overriden. This commit, first looks if the coc LSP process is started, if so, it does `call CocActionAsync('doHover')` as before but if no coc process is found, it does the default action of vim on pressing K button (which is normally opening up man page for the word under the cursor).
=> modified show_documentation function to do the default action of vim on pressing K when coc is not available

autoload/coc/list.vim
When `relativenumber` is set in vimrc.
Execute `:Coclist --number-select`:
Should be 
Execute `:Coclist`:
Should be:
=> fix(list): avoid `relativenumber`

src/handler/index.ts
When `"coc.preferences.hoverTarget": "preview"`, coc opens hover info in a preview window named `coc://document`.
However, that creates `document.swp` file in somewhere `&directory` indicates (typically in tmp directory), so when another instance of Vim opens hover info, the second Vim raises an error of "swap file already exists".
This fix prevents that by using `:noswapfile` when opening a preview window.
=> fix(handler): do not create swap file for preview window

src/completion/complete.ts
Fixed an issue where there were very few candidates for coc-tabnine completion.
A word in tabnine contains the same thing, so I think it's correct not to check dup if source is tabnine.
Is the existing implementation the intended one?
There are very few completion candidates for coc-tabnine, but with this change, the result is the same as VSCode.
VSCode:
Before:
After:
=> Fixed incorrect completion suggestions in TabNine

doc/coc.cnx, doc/coc.txt, src/handler/index.ts, src/plugin.ts
The `doHover` action currently reads its target configuration directly from preferences. This PR changes it so that the target argument can optionally be provided as an argument (falling back to reading from preferences), following the style of the `jumpTo*` actions. This is useful because sometimes one wants to use different keybindings for a preview hover or floating hover, or to keep some hovered information open in the preview while using mostly using the float.
I updated the docs except for the Chinese text, because I don't know Chinese.
=> add hover action target argument

src/diagnostic/manager.ts
The refreshOnInsertMode configuration flag was not being respected in case diagnostics were being set to the Ale plugin.
Apparently, this is a regression as this problem has been fixed in a previous PR: https://github.com/neoclide/coc.nvim/pull/1236/files
=> fix(ale): ensure refreshOnInsertMode is respected for Ale

autoload/coc/float.vim, autoload/coc/util.vim, doc/coc.txt
- Replace recent `coc#util#float_scroll_i` for something better named
- Add scrollbar synchronization
- Fix missing calculation of &scrolloff
- Nvim-only. Only useful for visual mode mappings (see added doc)
Partially solves #2521
=> Add coc#float#nvim_scroll() with synchronized scrollbar

data/schema.json, src/list/ui.ts
Calling `nvim_win_set_options` to set the statusline on each appended line prevents Airline from managing the status line based on the `filetype` setting, as described in their documentation.
This moves the status line segment configuration into the `coc-settings.json` file to allow for finer grained configuration of the status line in List windows. You can also set the configuration item to `null` to let Airline or other status line manager manage the statusline function directly.
=> Allow Status Line Config

README.md, autoload/coc/util.vim
The issue is that Fedora have package nodejs-yarn and it provides executable named `nodejs-yarn`.
In the source `yarn` executable is hardcoded.
That patch allow users to override name via global variable `g:coc_nvim_yarn`.
=> Let user override default yarn executable name.

src/handler/index.ts
I think it's ok not to run pclose before doing a hover with preview target because:
* Somtimes the preview doesn't open up on `CocActionAsync('doHover')`;
the preview window is just gone!
* Not doing `pclose` is not problem unlike `this.hoverFactory.close()` for float target:
it can reuse current `coc://document` buffer (bufnr preserved).
=> don't run pclose in onHover with target == 'preview'

doc/coc.txt, plugin/coc.vim, src/plugin.ts
This PR adds `:CocListCancel` which acts like a counterpart to `:CocListResume` allowing the list to be closed when the list is not the current window.
=> feat(list): Add cancel command

doc/coc.txt
Add constructor glyph to completionItemKindLabels example.
=> chore(doc): add constructor glyph example

doc/coc.txt
This resolves minor typos in the docs for CocSearch.
=> docs: fix a typo in CocSearch section

doc/coc.cnx, doc/coc.txt
Synchronize docs recently added in coc.txt to coc.cnx, make sure both have same content.
1. `Built-in configurations` section, without translation, tooo many configurations
2. key-mappings like `n_coc-classobj-a`
3. coc-variables like `b:coc_diagnostic_disable`
4. functions, `coc#util#api_version()`
5. commands, `CocSearch`
6. highlights, `CocMarkdownCode`
7. `coc-dialog`
=> docs: sync coc.txt to coc.cnx

data/schema.json, doc/coc.txt, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/manager.ts, src/list/basic.ts, src/list/formatting.ts, src/list/source/commands.ts, src/list/source/diagnostics.ts, src/list/source/extensions.ts, src/list/source/lists.ts, src/list/source/outline.ts, src/list/source/services.ts, src/list/source/symbols.ts, src/list/ui.ts, src/types.ts
This PR implements improved formatting options for CocList as proposed in #2630.  Specifically, it adds the option to align the content of CocLists in columns, making it look much nicer.
Additionally, it adds a couple options to configure what is shown in the diagnostics output, making the filepath and diagnostic-code configurable. 
Here the only the filename is shown, and the error code is completely hidden
Here a shortened version of the path is shown
=> Columnar alignment of CocLists

src/model/installer.ts
pnpm doesn't have the `--legacy-peer-deps` arguments, which results in an error when installing some extensions:
```
 ERROR  Unknown option: 'legacy-peer-deps'
Did you mean 'strict-peer-dependencies'? Use "--config.unknown=value" to force an unknown option.
For help, run: pnpm help instal
```
=> Fix extension installer with pnpm

data/schema.json, src/language-client/progressPart.ts
Add `workspace.progressTarget` configuration, default is `float`.
=> feat(language-client): progress notification for workDoneProgress

src/handler/signature.ts
fix `[coc.nvim]: Error on TextChangedI: Cannot read property '0' of undefined`
- using gopls(v0.6.0)
- type `(` when the cursor is at `|`
```go
package main
func main() {
func(){
// something
}|
}
```
=> fix(signature): check exist signature information parameters

src/handler/codelens/buffer.ts
I had this error happening in vim8.2:
and it turns out to be this line
=> fix(lens-destruct): default to empty object

src/handler/index.ts
`"coc.preferences.hoverTarget": "preview"` uses vim's markdown syntax
plugin, which usually highlights
<pre>
text
---
</pre>
as a markdown header. ~~To prevent this, insert a newline before '---'.~~
**Before**:
**After**:
* ~~This somehow doesn't add the newline for `"coc.preferences.hoverTarget": "float"`, so it won't disturb users using that option.~~
* Ideally, it'd be great if `"coc.preferences.hoverTarget": "preview"` can make use of the markdown renderer that `"float"` is using.
=> use empty line to delimit hover contents for preview target 

src/workspace.ts
Closes: https://github.com/neoclide/coc-tsserver/issues/246
=> fix(renameFile): doc returned from getDocument can be null

data/schema.json, doc/coc.cnx, doc/coc.txt
Signed-off-by: Zasda Yusuf Mikail <zasdaym@gmail.com>
=> Fix typo on list.source.symbols.exclude documentation

data/schema.json, src/__tests__/modules/util.test.ts, src/util/fs.ts, src/workspace.ts
When resolving the root directory, the current working directory is checked before doing a top-down search:
https://github.com/neoclide/coc.nvim/blob/f3b4a47780829f663740f1d276879060b45e8923/src/util/fs.ts#L63
In some cases, it is preferable to skip this check and *always* do a top-down search, particularly in some mono-repo setups.
This PR adds the option `workspace.workspaceFolderCheckCwd`, which defaults to `true`, so the default behaviour is unchanged. When this option is set to `false`, the current working directory is not checked.
=> feat(workspace): add option to disable cwd check when resolving root directory

autoload/coc/float.vim, bin/prompt.js
- `termwinkey` default to <kbd>C-W</kbd> in Vim, thus we must press <kbd>C-W .</kbd> to delete word -> set `termwinkey` to <kbd>C-\\</kbd> in prompt win buffer
- <kbd>ESC</kbd> is not recognized immediately in prompt win -> set `escapeCodeTimeout=0`
=> Improvements for prompt win in vim

src/extensions.ts
Sometimes I use logging to debug extensions, but I can’t see the properties inside and there is some confusion
=> feat: extension fields enumerable

src/attach.ts, src/workspace.ts
```
➜  coc.nvim git:(master) wc -l build/before.js 
65662 build/before.js
➜  coc.nvim git:(master) wc -l build/index.js 
65540 build/index.js
➜  coc.nvim git:(master) cat build/before.js | grep coverageDirectory
coverageDirectory: "./coverage/"
➜  coc.nvim git:(master) cat build/index.js | grep coverageDirectory 
➜  coc.nvim git:(master) 
```
and
```
➜  coc.nvim git:(master) cat build/index.js | grep "// package.json" -C 5 --line-number 
42957-  if (isParentFolder(os5.default.tmpdir(), root, true))
42958-    return false;
42959-  return true;
42960-}
42961-
42962:// package.json
42963-var version = "0.0.80";
42964-
42965-// src/workspace.ts
42966-var APIVERSION = 8;
42967-var logger24 = require_logger2()("workspace");
```
=> perf: tree-shaking package.json

src/diagnostic/buffer.ts
`diagnostic/manager` will sort diagnostics by severity `a.severity - b.severity`.
For example diagnostics from LS: `[{message: A, severity: 4}, {message: B, severity: 1}, {message: C, severity: 2}]`
After the sorting `[{message: B, severity: 1}, {message: C, severity: 2}, {message: A, severity: 4}]`.
Because `severity: 1`'s level is Error, the sorted diagnostics is OK in `:CocList diagnostics` or `CocDiagnostics`, error diagnostic will be listed at first.
But coc will setVirtualText following the sorted, this make `{message: A, severity: 4}` be displayed in virtual text. It's better to display error level diagnostic.
=> feat(diagnostic): reverse on virtualText

src/languages.ts
```
/**
* An data entry field that is preserved on a completion item between
* a [CompletionRequest](#CompletionRequest) and a [CompletionResolveRequest]
* (#CompletionResolveRequest)
*/
data?: any;
```
`completionItem.data` is used to preserve custom data for LS, should be set by LS. If LS didn't set data, coc should not set it, otherwise, LS checked `data` is not null, LS will try to get custom data in the `CompletionResolveRequest`, this makes an error. https://github.com/fannheyward/coc-rust-analyzer/issues/597
=> fix(languages): don't set item.data if undefined

src/model/document.ts
Our `getDocumentContent()` uses `\n`, but `applyEdits()` returns `\r\n`, causing redundant characters to appear on Windows
=> fix: applyEdits newline in win32

src/util/complete.ts
This pull request solve the issue descibed below.
I found coc.nvim cannot apply the textEdit as it is, when the start point of the range of this textEdit is after the start of the current word. For example, if I have a line like
```
bbbverynewtext
```
with the cursor at the end. Then I pressed `<TAB>` to select the entry like
```typescript
label: 'newText',
sortText: context.option.input,
filterText: context.option.input,
textEdit: {
range: {
start: { line: 0, character: 3 },
end: { line: 0, character: 14 }
},
newText: 'newText'
}
```
and I expect the text to be
```
bbbnewText
```
Sometimes coc.nvim gets it right, but most of the time I get some like
```
bbtnewText
bxtnewText
extnewText
```
However, if I selected this entry and confirm it with `<cr>`, then the textEdit will applied as I …
=> Fix textEdit when start of the range of the textEdit is after the start of current word

src/provider/codeActionmanager.ts
Fixes #2877
@chemzqm like discussed in #2877 [the vscode docs](https://github.com/microsoft/vscode-languageserver-node/blob/b90b25cc4c69824a948af71ec29e1e3c6de019d8/types/src/main.ts#L2722-L2729) state the following:
> Kinds are a hierarchical list of identifiers separated by `.`, e.g. `"refactor.extract.function"`
Meaning that it makes more sense to match the only using a startsWith (to catch only the base) rather than doing an exact match since the kind `quickfix` is a quickfix but `quickfix.something.else` is still a quickfix and should thus be matched by the only `quickfix`
I chose to do startsWith instead of splitting and checking the parts since it simplifies the code and also allows people to do some more rough matching if they want
=> Match code action on startsWith rather than exact match

src/workspace.ts
`deno lsp` returns `deno:/xxx` which is handled by VSCode, https://github.com/denoland/deno/issues/9514, coc only supports `deno://xxx`.
@chemzqm  I don't find any _stand_ format in LSP, so you can close if this may cause other problems.
=> fix(workspace): fire BufReadCmd for scheme:/

src/commands.ts, src/extensions.ts, src/list/source/commands.ts
Command of `onCommand:xxx` in `activationEvents` should be listed in `:CocList commands` and active the extension.
This bug was brought in by https://github.com/neoclide/coc.nvim/pull/2295 , should fix https://github.com/iamcco/coc-flutter/issues/63 cc @iamcco
=> fix(extensions): activate extension on command

doc/coc.txt
Small typo in the language server configuration section.
=> Fix typo in doc

src/language-client/client.ts
I find that it can not catch the error when execute command fail from server.
https://github.com/iamcco/coc-flutter/pull/100/files#diff-0119f9dcc1efa64d0039547840186bff37cca3aef54d6924b31510182a16d00eR48
=> feat(executeCommand): coc should not suppress error in executeCommand

src/completion/index.ts
`languages.registerCompletionItemProvider` with `' '` as trigger character, but shouldTrigger disable it before `sources.shouldTrigger`.
=> fix(completion): allow space triggerCharacter

data/schema.json, src/completion/complete.ts
The completion items will be sorted by score, priority, sortText etc, if none of these works, items will be sorted by defaultSortMethod `length` or `alphabetical`. Add `none` sort method, will follow upstream orders, that means coc doesn't sort them anymore.
=> feat(completion): add none default sort method

src/markdown/index.ts
Sometimes LS returns this code block in document, this will make markdown parser error. This fix just expands `\w+` and add `,` to it: `[A-Za-z0-9_,]`:
```
```compile_fail,E0392
struct Slice<'a, T> {
start: *const T,
end: *const T,
}
`` ` // add a space to here, make GitHub renders correctly
```
https://github.com/fannheyward/coc-rust-analyzer/issues/649
=> fix(markdown): improve markdown parser

autoload/coc/float.vim, autoload/coc/util.vim
Several Vim themes are broken with regards to concealments, especially in coc's popup. In many cases, user-defined concealments are hard to use or unwanted in the context of writing code.
While normally you can set their `conceallevel` manually as you wish, coc's popup/float feature **hardwires it** to `2`.
Here's a screenshot with the [`iceberg`](http://github.com/cocopon/iceberg.vim) theme. Several things, such as the `⛏️`, the bold  **`B`** for `bool`, the `.` instead of `::` in `llvm::cl`, or `⊥`  instead of `false` come from conceals.
Note how `☥` and `∅` in the normal code (behind the popup) looks okay.
As suggested, we will instead hardwire to `0`, resulting in no concealments:
=> feat(float): do not conceal in the floats

autoload/coc/highlight.vim
from documentation of matchaddpos:
`The maximum number of positions is 8.`
invoke matchaddpos repeatedly to solve this issue
=> fix(highlight): only support equal or less than 8 lines

README.md, autoload/coc/api.vim, autoload/coc/float.vim, autoload/coc/highlight.vim, autoload/coc/list.vim, autoload/coc/util.vim, data/schema.json, doc/coc.txt, src/__tests__/modules/sources.test.ts, src/__tests__/modules/textdocument.test.ts, src/channels.ts, src/completion/index.ts, src/extensions.ts, src/handler/helper.ts, src/handler/index.ts, src/handler/refactor/index.ts, src/handler/symbols.ts, src/language-client/client.ts, src/languages.ts, src/model/document.ts, src/model/outputChannel.ts, src/model/textdocument.ts, src/sources.ts, src/types.ts, tsconfig.json, typings/index.d.ts
add conf file for single js extension, config `activationEvents` and `contributes` for single js extension in `coc-extensions`.
ex:
```
% tree coc-extensions
coc-extensions
├── coc-ext.js
└── coc-ext.json
```
support config `coc-ext.js` in `coc-ext.json` like this:
```json
{
"activationEvents": ["*"],
"contributes": {
"configuration": {
"type": "object",
"title": "coc-ext configuration",
"properties": {
"coc-ext.enabled": {
"type": "boolean",
"default": true,
"description": "Enable coc-ext extension"
},
"coc-ext.debug": {
"type": "string",
"default": "debug",
"description": "debug"
}
}
},
"commands": [
{
"command": "coc-ext.Command",
"title": "coc-ext command title"
}
]
}
}
```
=> add conf file for single js extension

src/markdown/index.ts
hover from LS:
````
```rust
one: i32
```
````
after `parseMarkdown`, lines is `[ 'one: i32', '' ]`, there is a an unnecessary empty line.
=> fix(markdown): remove unnecessary empty line

README.md
neovim added support for `signcolumn=number` in neovim/neovim#12621, but `has("patch-8.1.1564")` doesn't work.
=> docs: add nvim version check for `signcolumn`

autoload/coc/highlight.vim
`synmaxcol` can be set to `0` to disable the maximum column syntax highlighting feature. The logic in `highlight.vim` led to nothing being highlighted if that was the case, this PR fixes that logic.
=> fix(autoload): allow synmaxcolumn to be 0

data/schema.json, src/markdown/index.ts
ignore `![alt](href)` in markdown text.
=> feat(markdown): ignore image in markdown doc

src/handler/symbols.ts, src/workspace.ts
When selectRange is missing and use visual mode, we should reselect
the selection.
An edge case like the current range is the same as the range that
languages server returned, coc will make n/vim lose the selection.
=> fix(symbols): keep visual selection after selecting range

autoload/coc/float.vim
If the user set a foldcolumn greater than 0, lines in dialog will wrap.
=> fix(float): should give foldcolumn a default value

doc/coc.txt
The default value in code is 100, but in help is 50
=> docs: inconsistent suggest.triggerCompletionWait value

autoload/coc.vim
"suggest.enablePreselect": true, neovim may use `nvim_select_popupmenu_item`
to preselect matched item which will fire `CompleteChanged` event to
redraw detail. We should use `noa complete()` to avoid unnecessary redraw.
=> fix(completion): avoid unnecessary redraw for floating window

autoload/coc/float.vim
The current implementation of the scrollbar on the tooltip that coc.nvim pops up is not displayed in the correct position in the Neovim GUI that supports multigrid ui. See: https://github.com/akiyosi/goneovim/issues/231
This fix resolves this issue.
The following is related information on this issue.
* https://github.com/neovim/neovim/issues/11935
* https://github.com/Yggdroot/LeaderF/issues/501
=> Avoid nvim_win_get_position for window position to support multigrid ui

src/plugin.ts
`:call showSemanticHighlightInfo` will show current buffer type tokens, and all type tokens that LS supported.
cc #3175
=> feat(plugin): list all token types LS supported

src/__tests__/handler/semanticTokens.test.ts
`yarn test-build` in my tests:
before: `74.41% Statements 14869/19982 61.42% Branches 6482/10553 72.91% Functions 2608/3577 76.69% Lines 13981/18230`
after.  : `75.03% Statements 14992/19982 61.82% Branches 6524/10553 73.39% Functions 2625/3577 77.34% Lines 14099/18230`
=> test(handler): add semanticTokens tests

doc/coc.txt, plugin/coc.vim, src/diagnostic/buffer.ts
This PR fixes the remaining entries in `DiagnosticHighlight` to use unique hlgroups, namely `Coc<Something>Highlight`, instead of reusing existing ones. Note that I say "remaining" because that enum was using `CocErrorHighlight` and `CocWarningHighlight` from the beginning (commit df7a1d94233bac9e26d593fe11f4f14b049e0a14, [relevant code](https://github.com/neoclide/coc.nvim/commit/df7a1d94233bac9e26d593fe11f4f14b049e0a14#diff-23ccea505c03101016c60ed7cbc58543c16d244e9b2fd5c3446ca3f7f7ced9bbR17-R24)), then `CocInfoFloat` was correctly replaced with `CocInfoHighlight` in commit 4cd2b40390a2dadb56baf3135064f74b148c9211, and finally I replace the remaining hlgroup for the "hint" severity with `CocHintHighlight` in this PR.
Additionally, I added the `CocDeprecatedHighlight` and …
=> fix(diagnostic): highlight hints, deprecated and unused text with their own unique hlgroups

Readme.md
Link errors occur on web browser plugin [Markdown Viewer](https://github.com/simov/markdown-viewer) and [GitLab Markdown Viewer](https://github.com/painyeph/GitLabMarkdownViewer).
=> link URL which starts with slash is unavailable

doc/coc.txt, plugin/coc.vim
Not sure if this was omitted intentionally, but the fact that there was no highlighting at all by default threw me for a loop!
---
This maps each of the "standard"[1] CocSem_* highlight groups to the
semantically-closest standard vim group, e.g. CocSem_enum => Type.
This means that a user with coc.nvim and a colorscheme enabled will get
some basic highlighting out of semanticTokens. Not enough to distinguish
everything, but at least e.g. types vs variables.
Today you get nothing by default, as the CocSem_* groups are undefined.
The possible downside: AFAICS coc.nvim doesn't apply highlight groups that
don't exist, so defining these groups means we'll pay the performance
cost of applying the styles even if the benefit is small.
[1] Specifically these are the SemanticTokenTypes defined in …
=> feat(semanticTokens): provide basic default colors

plugin/coc.vim
Maybe it's better to target master branch?
Reference: vim/vim#8544
Closes #3209
=> Fix command with complete but no nargs

src/handler/index.ts
Fix of undefined `selectionRange` handler attribute which leads to 
```
[coc.nvim]: Error on "rangeSelect": Cannot read property 'selectRange' of undefined
```
when calling `coc-range-select` command.
=> Fix: [coc.nvim]: Error on "rangeSelect"

autoload/coc/api.vim
According to the [nodejs client](https://github.com/neoclide/neovim/blob/neoclide/src/transport/base.ts#L75) and [nvim help](https://github.com/neovim/neovim/blob/master/runtime/doc/api.txt#L580-L586), my understanding is that the error return value of vim-api's `call_atomic` is different from that of neovim built-in, cause an unreadable [error](https://github.com/weirongxu/coc-explorer/issues/458) in vim.
=> fix(api): vim call_atomic exception list

typings/index.d.ts
Tested with 0.0.81-next.5, this should be optional.
=> feat(typings): make markdown optional

Readme.md
When installing the quickstart nodejs,   I got the following `permission denied` error. (Ubuntu 20.04.1 )
```
$ curl -sL install-node.now.sh/lts | bash
:
tar: include/node: Cannot mkdir: Permission denied
tar: include/node/openssl/bn_conf.h: Cannot open: No such file or directory
tar: include/node: Cannot mkdir: Permission denied
tar: include/node/openssl/dso_conf.h: Cannot open: No such file or directory
tar: include/node: Cannot mkdir: Permission denied
tar: include/node/openssl/opensslconf.h: Cannot open: No such file or directory
tar: include/node: Cannot mkdir: Permission denied
tar: include/node/openssl/dso_conf_asm.h: Cannot open: No such file or directory
tar: include/node: Cannot mkdir: Permission denied
:
```
This problem has been solved by using `sudo bash`.  It may help linux …
=> Avoiding permission errors when installing nodejs

src/workspace.ts
Happens due to a small order-of-execution bug.
=> fix: no way to set coc.preferences.maxFileSize from g:coc_user_config

src/language-client/index.ts
only regist semantic tokens when nvim/vim supported and configuration enabled.
Should disable semanticTokens highlighting when set `coc.preferences.semanticTokensHighlights` to false, #3175.
=> fix(language-client): regist semantic tokens

doc/coc.txt, src/__tests__/handler/hover.test.ts, src/completion/complete.ts, src/handler/hover.ts, src/handler/index.ts, src/languages.ts, src/plugin.ts, src/provider/definitionManager.ts, src/provider/manager.ts
VSCode: 
cc @chemzqm , some Todos:
~1. I put `definitionHover` in `handler` directly because we can use `locations` and `hover` to fetch and preview content, do we need to put into a new separate handler?~
~2. how to handle multiple definition locations? VSCode shows a `Click to show {0} definitions.` action, but we can't put action in hover by now~
~3. the definition content needs to be marked to markdown for highlighting~
=> feat(handler): definition content on hover

data/schema.json
Reword "format on type" to be clearer: "formatting on typing"
=> Documentation improvement in schema.json

data/schema.json, doc/coc.txt, plugin/coc.vim, src/__tests__/handler/callHierarchy.test.ts, src/__tests__/handler/locations.test.ts, src/__tests__/handler/outline.test.ts, src/__tests__/tree/treeView.test.ts, src/commands.ts, src/handler/callHierarchy.ts, src/handler/index.ts, src/handler/symbols/index.ts, src/handler/symbols/outline.ts, src/languages.ts, src/plugin.ts, src/provider/callHierarchyManager.ts, src/tree/BasicDataProvider.ts, src/tree/TreeItem.ts, src/tree/TreeView.ts, src/tree/index.ts, src/types.ts, typings/index.d.ts
Could works now, closes #1649
Added actions:
- `showIncomingCalls`
- `showOutgoingCalls`
Added commands:
- `document.showIncomingCalls`
- `document.showOutgoingCalls`
Todos:
=> [RFC] Support callHierarchy in tree view

autoload/coc/float.vim
When using `<esc>` to cancel the prompt window and go back to the previous window,
cursor shift one left.
Look like it's a bug for closing floating window in insert mode.
=> fix(float.vim): prompt canceled in neovim will move cursor

src/__tests__/modules/diagnosticManager.test.ts, src/diagnostic/manager.ts
autoRefresh and force are independent
close #3306
=> fix(diagnostic): disable refresh when !autoRefresh OR !force

src/__tests__/completion/basic.test.ts, src/completion/complete.ts
Some complete sources will return an empty result, but coc.nvim has cache
the previous results and reuse them.
Almost the invalid results will be filtered out later, but edge case
will pass the filter and still show it within the popup menu.
Solution: clean up the cache results earlier if the source return empty
This PR motivion from the below video:
https://user-images.githubusercontent.com/17562139/131810463-260a9b59-011f-4160-a7a9-428dd1bae86f.mp4
=> fix(completion): should clean previous items if empty source result

autoload/coc.vim
Call `nvim_select_popupmenu_item` only change pum_want struct, it means
that make preselect effective later which may delay or dither, or even
can't preselect correctly until the next event.
Known from the upstream source code, we can use `<Cmd>` or fire an event
manually to make preselect effective at once.
FYI:
- [nvim_select_popupmenu_item change pum_want](https://github.com/neovim/neovim/blob/5f8518b3f04c2295be24912dba78d3e34ca74b91/src/nvim/edit.c#L4757-L4766)
- [when to fire preselect](https://github.com/neovim/neovim/blob/5f8518b3f04c2295be24912dba78d3e34ca74b91/src/nvim/edit.c#L1031-L1052)
- [nvim_select_popupmenu_item test case](https://github.com/neovim/neovim/blob/5f8518b3f04c2295be24912dba78d3e34ca74b91/test/functional/ui/popupmenu_spec.lua#L260-L293)
=> fix(completion): preselect item at once

autoload/coc/float.vim, src/__tests__/markdown/index.test.ts, src/markdown/index.ts
Some terminals don't render the previous characters very well
**alacritty**
**windows terminal**
It's the character that makes the border
=> chore(ui): change character used to create lines

README.md
The link redirects to install-node.vercel.app/lts now, so I updated it in the github repo
=> Update install node.js link

src/model/installer.ts
Because some users have configured global npm, causes errors when installing extensions.
https://github.com/weirongxu/coc-explorer/issues/489
=> fix: Avoid extension install as global

autoload/coc/highlight.vim
Fix: #3473
This regression was introduced in 5f423c4a81698aac3c83adea7c1adad1549cb853
It affects users of https://github.com/altercation/vim-colors-solarized
Minimal reproduction can be found in the issue, in this comment: https://github.com/neoclide/coc.nvim/issues/3473#issuecomment-974731723
The issue is that there is only one reverse (in CocFloating -> Pmenu), and not in CocInfoSign as per this comment: https://github.com/neoclide/coc.nvim/issues/3473#issuecomment-974746261
|               | CocInfoSign cterm | CocErrorSign cterm | CocInfoSign gui | CocErrorSign gui |
| -- | -- | -- | -- | -- |
| Before regression | ![image](https://user-images.githubusercontent.com/4915682/142769938-230adcf4-0883-465a-9110-89f9038049c6.png) | …
=> fix(highlight): fix regression in highlight colour when only one colour has a "reverse"

src/markdown/renderer.ts
Resolves https://github.com/neoclide/coc.nvim/issues/3479
Old output:
New output:
=> Fix markdown rendering of horizontal rule (hr)

README.md
This fixes #3496 issue. CocActionAsync called instead of CocAction for OR (organize imports) command.
=> CocActionAsync called instead of CocAction for OR command.

autoload/coc/api.vim, autoload/coc/util.vim, src/extensions.ts
Neovim 0.6.0 has started to use globs in its default 'runtimepath' [1]. This prevented CoC from detecting extensions that are installed in `~/.config/nvim/pack/*/start/*`.
[1]: https://github.com/neovim/neovim/commit/9df7e02
I compared the output of `:CocList extensions` before and after applying the fix.
Before:
After:
=> fix: correctly handle globs in 'runtimepath'

src/workspace.ts
Result diff from two string from paths may wrong.
Like:
```
oldValue = '~/.local/share/nvim/site/pack/packer/opt/coc.nvim'
newValue = '~/.local/share/nvim/site/pack/packer/opt/coc-pyright,~/.local/share/nvim/site/pack/packer/opt/coc.nvim'
```
`fastDiff` will output ['-pyright', '~/.local/share/nvim/site/pack/packer/opt/coc']
Solution: split and diff
=> Fix watch rtp diff

autoload/coc/api.vim
I noticed that diagnostic messages cancel the semantic highlight on the next line. I haven't figured out why diagnostic affects semantic highlighting, but it seems that funcs.buf_clear_namespace is wrongly treating endLine as inclusive (VIM textprop ranges are 1-based end-inclusive, while LSP ranges are 0-based end-exclusive).
buf_clear_namespace  is used by
- coc#highlight#update_highlights
- coc#highlight#clear_highlight
Both seems to accept end-exclusive ranges.
=> funcs.buf_clear_namespace should treat endLine as exclusive

autoload/coc/highlight.vim
If two hightlight groups both are empty or single reverse attribute,
`coc#highlight#compose_hlgroup` can't build new highlight group.
Such as:
```vim
hi Group1 gui=reverse
hi clear Group2
echo coc#highlight#compose_hlgroup('Group1', 'Group2')
```
will throw E411: highlight group not found: FgGroup1BgGroup2
=> fix(highlight.vim): use default value for compose_hlgroup

src/__tests__/handler/format.test.ts, src/handler/format.ts
https://github.com/neoclide/coc-yaml/issues/51
I think the position used in `onTypeFormatting` is incorrect, in this fix, coc.nvim always uses the current position to request.
I've tested with rust-analyzer/yaml, works as expected. But this fix introduced an unexpected behavior for TS with tsserver:
```ts
if (obj) {
console.log(obj);
}
```
Put cursor on `if`, fire `cw`, the `if` will be removed and enter insert mode, tsserver returns onTypeFormatting, after applied the edits, you got:
```
(obj) {
console.log(obj);
}
```
the **space** after `if` is deleted too.
The reason:
1. coc will check `InsertEnter` and `TextChangedI`, try to do onTypeFormatting for `o` action
2. `cw` also fires these two event, and tsserver reposed to do formatting
=> fix(format): onTypeFormatting position

README.md
add <leader>cl for running code lens actions.
I found it very difficult to find any information on using code lens with coc. This piece of information I got from gitter, and would be nice to be in the documentation somewhere.
=> Add recommendation for code lens keybinding

src/workspace.ts
closes https://github.com/fannheyward/coc-deno/issues/124
the content is provided and loaded as Document, but filetype is incorrect
=> fix(workspace): detect filetype after jumpTo

src/configuration/shape.ts
If `coc-settings.json` file is not exists, `configuration.update()` will raise exception. This fix will create the file from `readFileSync` if not exists, the default flag is `r`, changed to `a+`:
- `r`: Open file for reading. An exception occurs if the file does not exist.
- `a+`: Open file for reading and appending. The file is created if it does not exist.
https://nodejs.org/api/fs.html#fs_file_system_flags
closes https://github.com/clangd/coc-clangd/issues/344
=> fix(configuration): create config file if not exist

autoload/coc/util.vim
The dst buf can't be listed after loaded. We should set buflisted for it manually.
=> fix(util.vim): bufadd doesn't set 'buflisted'

.editorconfig
`editorconfig` is used by many popular FOSS, we should add it.
=> chore(editorconfig): add editorconfig

doc/coc.txt, src/handler/rename.ts, src/model/fetch.ts
Hi there all! 
I thought I'd share a small tweak that I've enjoyed having implemented in my own setup for coc.
When renaming, I find it more "natural" for typing to have the user input window display without the previous name. This removes the need to hold delete to remove the old name, before entering a new one.
I decided to add a conditional statement to check for a new config key,`coc.preferences.fillRename`, to decide whether to pass a default value to `window.requestInput()`. 
Default is true, which keeps the functionality the same as currently. False means the floating window is empty and the user can immediately enter a new name!
Would love to hear what you think, and sorry in advanced if anything isn't setup correctly, this is my first official PR for a project!
Many thanks:)
=> Feat(rename.ts): Tweak To Refactor-Rename Floating Window

src/completion/index.ts
https://github.com/neoclide/coc.nvim/blob/77fb25aa6bd48061f78b91b99c10981843c9949a/src/completion/index.ts#L354-L357
Remove `latestInsertChar` checking.
=> refactor(completion): latestInsertChar alwayes to be true

doc/coc.txt
Just fixing a few typos here and there - I ran across "chagnes" and then
just went through the whole file with a spellcheck
=> fix(doc): Typos

data/schema.json
I tweaked the functionality to the rename feature in this PR (#3528).
It relies on the coc.preferences.renameFillCurrent setting in coc-preferences.json.
I missed adding this new key to `schema.json` so LSP support wasn't
working while editing `coc-preferences.json`. Hopefully this fixes that.
Thanks
=> fix(schema.json): Added schema for coc.preference.renameFillCurrent

src/model/installBuffer.ts
"remains" isn't the correct form of the word.
I elected to only change the form of the word in the message, rather than also correct the method and variable declaration. I'm not super familiar with what pieces might be a public API, and correcting them would serve no functional purpose.
Let me know if you want these updated and are safe to do so.
=> chore: Correcting verbiage of install message

src/sources/native/file.ts
1. `\u4E00-\u9FA5` for Chinese
2. `\u00A0-\u024F` for Latin-1 and Latin Extended-A/B https://en.wikipedia.org/wiki/List_of_Unicode_characters#Latin-1_Supplement
3.` \w` for word character
closes #3539
=> fix(sources): extend file sources regex

src/core/documents.ts
It was broken by the commit a4e83d1576e8a37e1449a5c235390f4bc27fc7ac.
=> fix(documents): fix maxFileSize when it is loaded from g:coc_user_config

autoload/coc/highlight.vim
0 based, no need to be subtracted 1
=> fix(highlight.vim): [end, 0] is exclusive for nvim_buf_get_extmarks

src/core/ui.ts
`call cursor(lnum, col)` lnum and col are byte related.
=> fix(ui): correct col of select range

src/services.ts
=> fix(services): respect users' settings of `disabledFeatures`

autoload/coc/highlight.vim
If `right_gravity` = false, inserting new line above `[row, 0, row, end_col]` extmark will
extend unexpected range which become [row - 1, 0, row, end_col],
and delta will be great than 0.
Press `[v:count]O` under one extmark that range is `[row, 0, row, end_col]` can easy to reproduce the issue.
=> fix(highlight): enable right_gravity for extmark

src/core/autocmds.ts
Fixed kotlin-language-server content provider uri.
kls jar uri is `kls:file:///path/to/jarFile.jar!/path/to/jvmClass.class`.
reference 
- lsp: https://github.com/fwcd/kotlin-language-server/blob/main/server/src/main/kotlin/org/javacs/kt/externalsources/KlsURI.kt#L26
- coc-kotlin: https://github.com/weirongxu/coc-kotlin/blob/master/src/languageSetup.ts#L109
When using `<amatch>`, resolved uri is `/home/user/repos/project/kls:file:///path/to/jarFile.jar!/path/to/jvmClass.class`  
When using `<afile>`, it can solve both `coc-java` and `coc-kotlin` problem.
=> fix: contentProvider uri

autoload/health/coc.vim
`:CheckHealth` is most popular in the `nvim` world, but can also be used on the vim side when rhysd's excellent `vim-healthcheck` plugin is installed: https://github.com/rhysd/vim-healthcheck
This is a minor change, one that allows the health checks to properly handle vim and determine if it is new enough.  For the minimum version checks I used the current values examined in `plugins/coc.vim`.
(This change doesn't address if the checks should report on the differences between the minimum supported and the optimal minimum.)
=> :CheckHealth should handle Vim

plugin/coc.vim
In NixOS, `gvim` is aliased to `vim -g`, so the `v:progname` is still `vim`.
=> fix: gvim detection in NixOS

src/tree/TreeView.ts
Always output the content of the selected node before
=> fix(TreeView): silent exe

esbuild.js
old: `coc.nvim version: 0.0.80-ccd0b050`
new: `coc.nvim version: 0.0.80-ccd0b050 2022-03-08 15:06:47 +0800`
Easy way to let users to know they're using an old version.
=> feat(esbuild): add commit date to CocInfo

yarn.lock
`npx yarn-dedupe`
before:
```
du -sh node_modules
239M	node_modules
```
after:
```
du -sh node_modules
175M	node_modules
```
=> chore(yarn.lock): clean up by removing duplicates

doc/coc.txt, src/tree/filter.ts
=> feat(tree-filter): allow <C-h> to delete character

data/schema.json
Just ran across a typo while browsing through `schema.json`.
=> docs(schema): Fix schema.json typo

data/schema.json, doc/coc.txt, src/handler/refactor/buffer.ts, src/handler/refactor/index.ts
=> add refactor.showMenu option

src/util/fs.ts
nodejs [Readline.close](https://nodejs.org/api/readline.html#rlclose)  doesn't close underlying input and output stream, will make file descriptor leak, leading to EMFILE error
main.go
```go
package main
import "fmt"
func main() {
fmt.Println("vim-go")
}
```
hello.go
```go
package main
func Add(x, y int) {
return x + z
}
```
I add some custom log
after `CocList diagnostics`
CocInfo
```
vim version: NVIM v0.7.0
node version: v16.13.2
coc.nvim version: 0.0.81-883870c5 2022-05-27 05:07:03 +0800
coc.nvim directory: /home/rammiah/.local/share/nvim/site/pack/packer/start/coc.nvim
term: tmux
platform: linux
2022-05-27T22:11:09.613 INFO (pid:1876850) [server] - file /home/rammiah/.config/coc/suggest.txt is open 
2022-05-27T22:11:09.634 INFO (pid:1876850) [services] - registered service …
```
=> fix(fs): close underlying file manually to avoid EMFILE

data/schema.json, doc/coc.txt, src/__tests__/core/workspaceFolder.test.ts, src/core/workspaceFolder.ts
```json
{
"workspace.workspaceFolderCheckCwd": false,
"workspace.bottomUpFiletypes": ["*"],
}
```
is extremely useful for the git submodule to find a correct workspace.
=> feat(workspaceFolder): support wildcard for bottomUpFiletypes

src/handler/semanticTokens/buffer.ts
have no idea why delta.data is undefined
=> fix(semanticTokens): check delta.data

autoload/coc/util.vim, src/core/files.ts
On Windows, due to Vim's bug, you can't correctly `fnameescape()`
special characters in buffer name.
(reference: https://github.com/vim/vim/issues/541)
Therefore, you can't open a buffer whose name contains some special
character with `:edit`, preventing correctly jump to definition in some
LSPs. For example, jdtls returns custom URI (jdt://...) if the
definition is inside metadata. This URI contains `?`, so it can't be
opened in Windows (https://github.com/neoclide/coc-java/issues/82).
I found that you can workaround this bug using Neovim API to set a
buffer name directly, though it's Neovim-only solution.
Fixes #2748.
=> fix(files): workaround buffer name limitation on Windows (Neovim)

autoload/coc/util.vim, src/core/files.ts
This improves the workaround introduced in #3904 and #3907. The previous
implementation is using Neovim-only API, but new implementation uses
`bufadd()` to create the buffer with specified name, so it works on Vim
too.
With quick testing, it seems that new implementation works without issue
like #3906 even if non-URI like path was given, so you may not have to
check it looks like URI, but keep it for now to reduce the risk of
potential breakage.
Sorry for sending a patch again and again.
=> fix(files): Workaround Windows path limitation on Vim too

autoload/coc/highlight.vim
Sometimes changing the theme will cause the highlighting to be cleared. I don't know if there is a better way to check, if so then close this pr
=> fix(compose_hlgroup): check hlGroup if is cleared

autoload/coc/notify.vim
This can throw an error when less than 0, due to [this check](https://github.com/neovim/neovim/blob/feba56af7d032c948a78c21735502bebe45f8361/src/nvim/api/extmark.c#L876-L878) in Neovim.
Error message looks like:
```
2022-07-29T14:28:26.870 ERROR (pid:128515) [node-client] - request error on "nvim_call_function" [
'coc#notify#create',
[
[ 'Select how LSP should resolve this macro:' ],
{
broder: true,
focusable: true,
marginRight: 10,
timeout: 10000,
maxWidth: 60,
maxHeight: 10,
highlight: 'CocFloating',
winblend: 30,
disabled: false,
source: 'coc.nvim',
kind: 'info',
borderhighlight: 'CocNotificationInfo',
actions: [Array]
}
]
] Vim(call):E5555: API call: Column value outside range Error: 
at NeovimClient2.request (/home/noah/personal/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:29 …
```
=> Set minimum for col_start highlights to 0

autoload/coc/ui.vim
The previous pattern accidentally matched with "safe_pumvisible()"
or similar so I prepend "\<" to clarify the word.
```vim
function! s:safe_pumvisible() abort
try
return coc#pum#visible()
catch /^Vim\%((\a\+)\)\=:E117:/
return pumvisible()
endtry
endfunction
inoremap <expr> <CR> <SID>safe_pumvisible() ? ....
```
=> fix(pum): fix regex pattern on keymapping check

autoload/coc/pum.vim
Problem: `coc#pum#next()` and `coc#pum#prev()` trigger modeline evaluation.
Solution: Pass `<nomodeline>` to `doautocmd`.
Related: #2292
=> fix(pum): use <nomodeline>

src/handler/signature.ts, typings/index.d.ts
`??` has higher precedence than `? :`
=> fix(signature): fix activeParameter

autoload/coc/float.vim
The current implementation of the tooltip position associated with pum is not displayed in the correct position in the Neovim GUI that supports multigrid ui. 
This fix resolves this issue.
The following is related information on this issue.
https://github.com/neovim/neovim/issues/11935
Yggdroot/LeaderF#501
https://github.com/neoclide/coc.nvim/pull/3150
=> fix(ui): Consider multigrid UI for float window placement

autoload/coc/float.vim
Remove `Search` highlight added by `/` command in floats.
See the example:
https://github.com/neoclide/coc.nvim/discussions/4016#discussioncomment-3345247
Adds `Search:` to `&winhl`.
Note that it's intentional that the second argument is empty, which effectively removes the definition of the specified highlight.
=> Remove Search highlight in floats

autoload/coc/float.vim
`Search:` had accidentally removed in this commit:
https://github.com/neoclide/coc.nvim/commit/578d2e348a15d9e0d653f3c4859eb65c74ce9c5e
=> Revive `Search:`

autoload/coc/pum.vim
=> fix(completion): reset input word even it is empty string

src/diagnostic/buffer.ts
There is a suffix given on each line with diagnostic virtual text that says `xyz` and is highlighted with `MoreMsg`.
=> fix(diagnostic): "xyz" suffix after each virtual text line

data/schema.json, doc/coc-config.txt, src/diagnostic/buffer.ts, src/diagnostic/manager.ts, src/diagnostic/util.ts
Add a option `diagnostic.virtualTextAlign` to set the diagnostic virtual text position.
=> feat(diagnostic): Add 'diagnostic.virtualTextAlign' to set the position of virtual text

CONTRIBUTING.md
the original [coc-tslint-plugin](https://github.com/neoclide/coc-tslint-plugin) seems to be outdated in favor of [coc-eslint](https://github.com/neoclide/coc-eslint)
=> docs(contributing): change javascript linting provider

data/schema.json, doc/coc-config.txt, doc/coc.txt, src/__tests__/snippets/session.test.ts, src/snippets/manager.ts, src/snippets/session.ts
My snippets often include _optional_ placeholders, e.g. the "name" of this snippet can be deleted to create an anonymous function:
```vim-snippet
snippet fn "function"
function ${1:name}(${2:params}) {
${0:${VISUAL}}
}
endsnippet
```
In such cases, after activating the snippet and I have `name` selected, I hit backspace to delete it. Even though I've fully removed it, the `name` placeholder is still the selected one. So I have to _manually_ jump to the next placeholder (`params`).
This new option, `coc.preferences.nextPlaceholderOnDelete`, makes it so that when a placeholder is completely removed from the document, coc _automatically_ jumps to the next placeholder.
Please note: this is my first contribution. :) So I'm a little unsure of whether I got everything right. In particular I have …
=> Add nextPlaceholderOnDelete option

data/schema.json, doc/coc-config.txt, src/__tests__/modules/diagnosticBuffer.test.ts, src/diagnostic/buffer.ts, src/diagnostic/manager.ts, src/diagnostic/util.ts
1. Add `diagnostic.virtualTextFormat` (maybe `virtualTextPrefix` can be deprecated?)
2. Fix virtual text diagnostics shown order `arr.push(...)` --> `arr.unshift(...)`. This is because the diagnostics have been sorted by `severity`, but the `for ... in` loop is reverved. This change ensures that high-severity diagnostic message shown first
=> feat(diagnostic): Support "diagnostic.virtualTextFormat" to define virtual text format

autoload/coc/color.vim, autoload/coc/float.vim, autoload/coc/highlight.vim, doc/coc.txt, plugin/coc.vim
Some color schemes uses high contrast color with `Pmenu`, which not looks good with other highlights.
For example solarized:
This PR creates new colors when the contrast between `Pmenu` and `Normal` > 4 by lighten or darken the `Normal` highlight group.
Need to test more color schemes for better delta value.
=> Create new colors for float windows when necessary

autoload/coc/api.vim, src/handler/hover.ts
I was having an issue with the hover preview functionality in vim. Every time I tried to force coc to use a preview window I got the following error:
```
2022-09-14T15:34:19.377 INFO (pid:3578083) [attach] - receive notification: doHover [ 'preview' ]
2022-09-14T15:34:19.436 ERROR (pid:3578083) [node-client] - call_atomic request error VimException(String) on "nvim_command" [ `if winnr('j') != winnr('k') | exe "normal! z12\\<cr> | endif"` ] Vim(endfunction):E171: Missing :endif on function co
c#api#call[4]..304[5]..BufReadCmd Autocommands for "coc:/*"..function coc#rpc#request[4]..<SNR>79_request[5]..coc#api#call[4]..298[6]..304, line 12 Error
at BH.resumeNotification (/home/user/.vim/bundle/coc.nvim/build/index.js:23:1302)
at $H.resumeNotification …
```
=> fix(hover): move quotation mark to correct scope

plugin/coc.vim
* `CocMenuSel ctermbg=237 guibg=#13354A` is not distinguishable in https://github.com/lifepillar/vim-solarized8
* [line 432](https://github.com/neoclide/coc.nvim/blob/01ddea57674bf36512923e37e45510577f36dc18/plugin/coc.vim#L432) already checked `background == darak`, so no need to check in [line 429](https://github.com/neoclide/coc.nvim/blob/01ddea57674bf36512923e37e45510577f36dc18/plugin/coc.vim#L429)?
=> fix(plugin): fix CocMenuSel in dark background

src/__tests__/modules/installer.test.ts, src/model/installer.ts
In #2671 I removed `--legacy-peer-deps` option when installing extensions with pnpm, but the correct fix is to use a equivalent option to match this behavior.
This pull request will prevent unmet peer dependencies error when installing some extensions with pnpm, such as [coc-explorer](https://github.com/weirongxu/coc-explorer).
=> fix(installer): fix pnpm unmet peer deps error

autoload/coc.vim, doc/coc.txt, plugin/coc.vim, src/__tests__/configuration/configurationModel.test.ts, src/__tests__/configuration/configurations.test.ts, src/__tests__/core/editors.test.ts, src/__tests__/handler/highlights.test.ts, src/__tests__/handler/search.test.ts, src/__tests__/list/sources.test.ts, src/__tests__/modules/services.test.ts, src/__tests__/modules/workspace.test.ts, src/__tests__/snippets/parser.test.ts, src/configuration/configuration.ts, src/configuration/event.ts, src/configuration/model.ts, src/cursors/index.ts, src/language-client/codeAction.ts, src/plugin.ts, src/services.ts, src/sources/index.ts, src/sources/native/around.ts, src/sources/native/buffer.ts, src/sources/native/file.ts, src/tree/TreeView.ts, typings/index.d.ts
Non-trivial change: Correct `regist` to `register`. Add a new API for `register` and claim `regist` is deprecated.
=> chore: fix typo

doc/coc.txt, plugin/coc.vim, src/__tests__/handler/inlayHint.test.ts, src/handler/inlayHint/buffer.ts
According to the InlayHint kind, apply different highlight group. This behavior is similar to the display in JetBrains/WebStorm.
This PR add the new highlight groups `CocInlayHintParameter` `CocInlayHintType`, they default link to `CocInlayHint`. 
Vim
=> feat(InlayHints): Highlights by InlayHint kind

.editorconfig, autoload/coc/highlight.vim, lua/coc/highlight.lua
For now,  coc.nvim use Vimscript to drive highlighting, but Vimscript is slow enough. After opening https://github.com/tree-sitter/tree-sitter-javascript/blob/936d976a782e75395d9b1c8c7c7bf4ba6fe0d86b/src/parser.c#L70311, coc.nvim makes neovim lagging.
The bottleneck is in https://github.com/neoclide/coc.nvim/blob/488d6ae762f905f58a362294bab0af2150d0c399/autoload/coc/highlight.vim#L737-L743
TBH, I hope coc.nvim can hug the Lua.
=> perf(highlight.lua): add lua highlight to reduce blocking

README.md
- use `vim.keymap.set()` to replace `vim.api.nvim_set_keymap()`
- thanks to [this commit](https://github.com/neovim/neovim/commit/6d41f65aa45f10a93ad476db01413abaac21f27d), `vim.keymap.set` is higher level than `vim.api.nvim_set_keymap`.
- One obvious benefit is that we can direct call lua function in `vim.keymap.set`
- adjust some position of code
=> Improve readibility of readme.md

README.md
The change I introduced in #4270 was not correct. It made it so that `<TAB>` worked anywhere on a line but not at the beginning of the line. This reverts that change and applies the correct fix.
The difference between the vimscript solution and the Lua one is that vimscript `=~#` returns a `bool` while Lua's `match` returns [the captures from the pattern](http://www.lua.org/manual/5.4/manual.html#6.4) or `fail` which seems to get converted into `nil` somewhere.
=> fix(README): reverts #4270 and applies the correct fix

data/schema.json, doc/coc-config.txt, src/handler/inlayHint/buffer.ts
This controls if inlayHints should be displayed enabled by default.
Allowing you to have inlay hints enabled but not displayed by default.
=> feat(configuration): Add display config to inlayHints

doc/coc.txt
I have made some small changes in the `coc-completion` section of the documentation to make it easier to read.
=> docs: Make completion documentation easier to read

autoload/coc/snippet.vim
This PR addresses a bug where `"suggest.preferCompleteThanJumpPlaceholder": true` is ineffective with the custom PUM.
=> Fix coc#snippet#jump to factor in coc#pum#visible

src/handler/locations.ts
previously, the commands generated by the CoC tagfunc produced output that caused the press-enter dialog to appear when selecting from multiple options with g<C-]>. make the commands silent so that this doesn't happen.
the commands themselves are still displayed in the g<C-]> dialog when there are multiple options, which may potentially confuse a user. a better choice might be to replace cmd with the exact string that matches the tag, like the native tagfunc does.
=> make tagfunc cmds silent

autoload/coc/list.vim
We don't need to show colorcolumn in list window.
=> feat(list): avoid highlight colorcolumn in list window

autoload/coc/pum.vim
```vim
inoremap <silent><expr> <CR> coc#pum#visible()
\? coc#_select_confirm()
\: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
fix add `0` to the end of completion item.
=> fix(select_and_confirm): return ''

data/schema.json, doc/coc-config.txt, src/handler/format.ts
If `formatOnSave` is enabled, and the format command takes longer than 500ms to run, it will time out and the file will not be formatted. Add a way to configure the timeout to address slow linters. (This is a companion change to `coc.preferences.willSaveHandlerTimeout`.)
=> Add coc.preferences.formatOnSaveTimeout

src/handler/semanticTokens/index.ts
Yeah, remember #4392? Turns out you forgot to change `index.ts` so when you call `semanticTokens.checkCurrent` the issue persists.
=> fix(semanticTokens): make indexing of highlight groups more consistent

src/util/diff.ts
modify function `patchLine`, let it filled character align by byte, avoid it causing bug at fuzzy match highlights like this:
=> fix bug: patchLine, byte aligned

autoload/coc/api.vim, src/__tests__/vim.test.ts
Fix Buffer.getVar() on vim.
Related issue: https://github.com/weirongxu/coc-explorer/issues/563
=> fix(api): Fix Buffer.getVar() for non-current buffer

autoload/coc/string.vim
In `coc#string#content_height`, coc uses the `breakat` option to determine where to break a line when it's too long. However, the option value is not properly escaped.
For example, `set breakat=\ !@-+;:,./?` can lead to `request error on "nvim_call_function" - Vim(for):E944: Reverse range in character class` when lines need to be broken. In this case, the generated `pattern` is `[ !@-+;:,./?]\zs` where `@-+` is a "reverse range." The fix is to escape `-` as well.
=> fix(util): properly escape breakat

src/list/source/extensions.ts
The buffer is empty due to the file not existing.  `file:///Readme.md`
**Log**:
```
2023-05-24T17:35:46.639 DEBUG (pid:44710) [core-documents] - buffer created 6 true file:///Readme.md
```
**Log**:
```
2023-05-24T17:36:41.713 DEBUG (pid:44813) [core-documents] - buffer created 7 true file:///Users/yaegassy/.config/coc/extensions/node_modules/coc-tsserver/Readme.md
```
=> Fix the issue of opening an empty buffer in the help action of the :CocList extensions

README.md
rm `coc-codeaction`
close #4509
=> chore(README): improve mappings

.github/workflows/ci.yml
=> feat(ci): test with nvim nightly

doc/coc.txt
docs(coc.txt): Correct spelling resutl to result
Correct spelling error in doc/coc.txt, Line: 2379<br>
resutl was corrected to result
```text
When callback function exists as the last argument, the callback
function is called with `error` string as the first argument and
-	`resutl` as the second argument.  When no callback exists, error
+	`result` as the second argument.  When no callback exists, error
message would be echoed.
Chceckout |coc-actions| for available actions.
```
Using grep I found no other reference to the word resutl in the projects structure. I'm not knowledgeable enough to know what is going on with the CocActionAsync function so please let me know if their are any problems with this PR. I've only made one other PR to an actuall project, Vim, the others being …
=> docs(coc.txt): Correct spelling resutl to result

doc/coc.txt
=> docs: update outdated url

src/__tests__/modules/workspace.test.ts, src/core/funcs.ts
For now, ls provider's score will be equal to the default one if ls provider's documentSelector has pattern. For example, a ls registers capability `textDocument/documentHighlight` with documentSelector `{'language': 'cs', 'scheme': 'file', 'pattern': '**/*.cs'}`, it will get score 5, which is equal to the default one with documentSelector '*', even if the language id has matched. Since the capability is registered later than the default one, DocumentHighlightManager will only use the default one to provide highlight, which is not expected.
If all of language, scheme, and pattern match, we should return the highest score of them, instead of the last score.
=> fix: ls provider's score is equal to the default one

src/handler/format.ts
otherwise language-override configuration like this won't work, always default value
```json
"[python]": {
"coc.preferences.formatOnSaveTimeout": 5000
},
```
closes https://github.com/fannheyward/coc-pyright/issues/951
=> fix(format): formatOnSaveTimeout config with scope

autoload/coc/list.vim, src/list/mappings.ts
Closes #4643
use `coc#float#scroll_win` to scroll float/popup window, same as hover
=> fix(list): scrolling float preview for vim

src/model/input.ts
=> fix(input): bdel term buf

autoload/coc/util.vim
https://github.com/neoclide/coc.nvim/issues/4491
`$XDG_CONFIG_HOME` exists but invalid, don't use it as data home.
=> fix(util): check $XDG_CONFIG_HOME before use as data home

src/__tests__/completion/sources.test.ts, src/completion/native/file.ts
=> fix(native): get filepath from line by cursor position

src/__tests__/core/fileSystemWatcher.test.ts, src/core/watchman.ts
See https://github.com/neoclide/coc.nvim/issues/4616#issuecomment-1536972714
=> Allow watching workspaces at /tmp/some-dir

data/schema.json, doc/coc-config.txt, src/__tests__/handler/inlayHint.test.ts, src/handler/inlayHint/buffer.ts
needs https://github.com/neovim/neovim/pull/20130
Next:
- inlayHint.subSeparator
- inlayHint.typeSeparator
- inlayHint.parameterSeparator
Do we need to support both `inline` for nvim 0.10.0+ and `eol` for nvim 0.9.0-? I do like only `inline`, for nvim 0.9.0 and before, no inlayHint
=> feat(inlayHint): inline display for nvim

src/__tests__/handler/locations.test.ts, src/handler/locations.ts
From LSP specification, Position.character indicates the character offset on a line in a document (zero-based) [1]. However, `|` in vim will jump to screen column [2]. If the file (e.g., linux kernel source code) uses tabs for indentation, then CocTagFunc will jump to a wrong position. We can fix it by changing to use `cursor()`, whose col argument means the byte-count column.
1. https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position
2. https://vimdoc.sourceforge.net/htmldoc/motion.html#bar
=> fix: CocTagFunc jumps to wrong position if using tabs for indentation

src/model/dialog.ts
Currently if `close: false` is passed, it won't be set to `opts`.
https://github.com/neoclide/coc.nvim/blob/e10877749538a9875e359abe69974b0d0ca697ca/src/model/dialog.ts#L97
As a result, `coc#dialog#create_dialog` will consider `opts.close` not set and use `1` as a fallback.
https://github.com/neoclide/coc.nvim/blob/e10877749538a9875e359abe69974b0d0ca697ca/autoload/coc/dialog.vim#L300
This PR makes sure `opts.close = 0` is properly set.
=> FIx `opts.close` for `window.showDialog`

src/core/autocmds.ts
=> fix: keep autocmds on registering new one

README.md
This updates the README to reflect the new version of Node.JS required by 5385efd.
=> Update README.md with Node.JS version required.

doc/coc-api.txt, src/diagnostic/manager.ts
Fix typo in all files containing `curosr` => `cursor`
=> docs: Fix typo curosr => cursor

autoload/coc/pum.vim, src/attach.ts, src/completion/index.ts
Fixes #4823.
- Allow `CompleteStop` as a `request` call
- Do not ignore promise in stop() and await all
=> fix: block Vim until completion resolve finishes

autoload/coc/prompt.vim, doc/coc.txt, src/list/configuration.ts
As described in title, this PR allows user to map two additional keys: `<C-space>` and `<C-_>` (this is equivalent to pressing `Ctrl` and `/`).
Personally, I bind `<C-space>` to toggle preview, and `<C-_>` to show help (since `/` and `?` are the same key).
If we run `:echo nr2char(getchar())` and press `Ctrl+Space` or `Ctrl+/`, we get the relevant string output as expected.
**Question**: Is there a way to automate the above test? Or are we comfortable relying on Vim's testing:
- `<C-space>` is also tested in Vim: [keycode_check.vim](https://github.com/vim/vim/blob/7062be13129985fe297b9a8e59c57b8f0db61b8f/src/testdir/keycode_check.vim#L75).
_Thanks again for this wonderful plugin; coc.nvim has been always been a joy to use!_
=> chore(list): support <C-space> and <C-_> mappings

doc/coc.txt, src/__tests__/list/mappings.test.ts, src/list/mappings.ts, src/list/prompt.ts
Support moving left and right in list prompt (similar to `forward-word` and `backward-word` in [GNU Readline][gnu-readline]).
[gnu-readline]:http://git.savannah.gnu.org/cgit/readline.git/tree/doc/readline.info?id=5d4d92f221d6aac4be445bdd8cd9b48d9ac33f04#n1064
Added unit test in `list/mappings.test.ts`.
=> chore(list): support moving by word in prompt

src/diagnostic/buffer.ts, src/types.ts
add `DiagnosticWithFileType` to support highlight diagnostic buffer
I am currently working on porting https://github.com/yoavbls/pretty-ts-errors to coc (https://github.com/hexh250786313/coc-pretty-ts-errors). It requires that the diagnostic's floating buffer supports a custom filetype to highlight and format the diagnostic information. And the PR is for this purpose.
=> feat(diagnostic): add `DiagnosticWithFileType`

autoload/coc/api.vim, autoload/coc/highlight.vim
**this PR fixes issues #4879 and #4872**
[#4879] list slicing is used in the function "s:add_highlights_timer", instead of a very slow for loop
[#4872] ignore error E964
=> fix issues #4879 and #4872

src/completion/native/around.ts, src/completion/native/buffer.ts, src/completion/native/file.ts
otherwise, `coc.source.around.disableSyntaxes` won't work.
=> fix(native): checkComplete for file/buffer/around

autoload/coc/window.vim
`nvim_win_get|set_option` are deprecated
https://github.com/neovim/neovim/pull/23670
=> refactor(window): use nvim_get|set_option_value

src/core/workspaceFolder.ts
In monorepo, cached workspaceFolder maybe wrong for document. I didn't find a better way for this, just disable the cached one.
https://github.com/fannheyward/coc-pyright/issues/680
=> fix(core): disable cached-dir for resolving root

src/handler/codelens/buffer.ts
coc will resolve codeLens onChange/onMove etc, with codeLens in current visible range, then display in virtualText.
If the codeLens.position = top, and outside the current visible, coc won't clear them, and add another line in virtualText.
Clear all on resolving before setting again.
Closes https://github.com/fannheyward/coc-rust-analyzer/issues/1112
=> fix(codeLens): clear whole buffer on resolving

src/configuration/util.ts, src/language-client/configuration.ts
=> fix(configuration): merge dotted config key

autoload/coc/highlight.vim
Closes #4872
only effect vim with `set nohidden`
=> fix(highlight): check buffer exist to highlight

src/handler/symbols/index.ts
Closes #1847, temporarily workaround fix, don't decrease end.line for Python
To make `coc-funcobj-a/i` to work as expected, the code should be formatted first.
=> fix(symbol): don't decrease end.line for Python

src/model/document.ts
This fixes issue like https://github.com/neoclide/coc.nvim/issues/4873 on Vim, but https://github.com/neoclide/coc.nvim/blob/392264f475aea82419b493cec368b0bcf5ca40ee/src/model/document.ts#L648-L655 won't called anymore.
I've checked https://github.com/neoclide/coc.nvim/commit/930c6dc09c2c9db5d648d07033025d808283ec90, but still can't get the original logic, needs more tests.
Before this change, vim couldn't get correct lines of buffer as nvim.
=> fix(model): fire onTextChange on TextChangedI

src/language-client/diagnostic.ts
https://github.com/yaegassy/coc-volar/pull/327
1. LSP 3.16 and before, only push mode, server `publishDiagnostics`
2. LSP 3.17 added `refreshSupport`, server will ask client to refresh from `workspace/diagnostic/refresh`
3. LSP 3.17 also added pull mode, server provides `diagnosticProvider`, client pull diagnostics onSave/onChange etc
coc.nvim enabled `refreshSupport` but didn't onRequest DiagnosticRefreshRequest, could't handle `workspace/diagnostic/refresh`. Because no `diagnosticProvider`, coc.nvim cancelled registration.
=> fix(language-client): register DiagnosticRefreshRequest

autoload/coc/list.vim
If the user uses `foldcolumn` then the list buffers have an extra column that is not useful especially for a buffer that is bound to only be in insert mode. This locally sets `foldcolumn=0`
=> fix(list): set foldcolumn to 0 since it isn't applicable

src/handler/inlayHint/buffer.ts
If the chunk is an array with a single string, the highlight group only uses the foreground of `Normal`, which makes `cursorline` look better.
Reference: https://github.com/neovim/neovim/blob/0f85aeb478a68c18a8195e69724e1cb618fec058/runtime/lua/vim/lsp/inlay_hint.lua#L333-L337
=> fix(inlayHint): more compact padding highlight group

src/list/mappings.ts
This should allow the expression function to return nil, to by default execute the default action of the list, as there are no easy ways to extract the name of the default action for the current list. doAction by default if no 'name' is provided would fallback to the defaultAction.
=> fix(defaultAction) fallback to default action on emtpy expression

.github/ISSUE_TEMPLATE/bug_report.md, README.md, autoload/coc/list.vim, src/__tests__/list/sources.test.ts, src/list/source/diagnostics.ts
Closes https://github.com/neoclide/coc.nvim/issues/4952
`:CocList diagnostics --buffer`
=> feat(list): add --buffer to list buffer diags

autoload/coc/list.vim, history.md, src/__tests__/list/sources.test.ts, src/list/source/diagnostics.ts
In addition to the recently added `--buffer` option, i have also added a `--workspace-folder` which will show only the ones active for the current workspace folder.
=> Add workspace folder filter argument for diagnostics

.github/workflows/ci.yml
Python 3.12 can cause issues because `distutils` was removed from the Standard Library.
=> chore(CI): use Python 3.12

src/handler/inlayHint/buffer.ts
related https://github.com/neoclide/coc.nvim/pull/4950
Set hl group for hint in Vim
=> fix(inlayHint): hl_group for vim

src/completion/complete.ts, src/completion/source-language.ts
Closes #4877
also fix MAX_TIMEOUT https://github.com/neoclide/coc.nvim/pull/1608
=> fix(completion): dont block completionItem.command

autoload/coc/vtext.vim
Closes #4817
without bufnr will use current buffer
=> fix(vtext): add bufnr to vim's prop_add

data/schema.json
change to `language-overridable`
Closes #4978
=> feat(schema): change scope of codeLens configs

src/extension/installer.ts, src/handler/refactor/search.ts, src/list/commandTask.ts
Closes https://github.com/neoclide/coc-prettier/issues/178
Latest version of Node.js needs to set `shell: true` to spawn option
- https://github.com/node-red/node-red/pull/4652
- https://github.com/microsoft/rushstack/pull/4637
=> fix(spawn): add `shell:true` on windows

src/extension/installer.ts
Closes #4987
on windows, command should be quoted if containing spaces. https://github.com/nodejs/node/issues/7367
=> fix(extension): quote cmd on windows

src/list/manager.ts
List action works on lastSession. When resuming a named list which is not the lastSession, it should update the lastSession.
This fix #4971 case2.
=> fix(list): update lastSession when resume list by name

esbuild.js
Disabling minify will increase the `build/index.js` file size from 2.1M to 3.9M, but this provides clear trace line information for debugging when using the release branch
=> feat(esbuild): disable minify for all

data/schema.json, history.md, src/__tests__/completion/basic.test.ts, src/completion/index.ts, src/completion/pum.ts
to control re-trigger or not after indent changes
Closes #4713
=> feat(completion): add reTriggerAfterIndent

src/handler/workspace.ts, src/window.ts
Add parameter to command `workspace.showOutput`, let user could control  how to open the `OutputChannel` window in  command mode like this:
`:CocCommand workspace.showOutput channelName sp`
=> Add parameter to command 'workspace.showOutput'

README.md, autoload/coc.vim, autoload/coc/client.vim, autoload/coc/compat.vim, autoload/coc/dialog.vim, autoload/coc/float.vim, autoload/coc/highlight.vim, autoload/coc/list.vim, autoload/coc/prompt.vim, autoload/coc/pum.vim, autoload/coc/snippet.vim, autoload/coc/task.vim, autoload/coc/util.vim, autoload/coc/vtext.vim, autoload/coc/window.vim, autoload/health/coc.vim, doc/coc-example-config.vim, doc/coc.txt, history.md, plugin/coc.vim, src/__tests__/handler/inlayHint.test.ts, src/__tests__/handler/semanticTokens.test.ts, src/completion/index.ts, src/handler/colors/colorBuffer.ts, src/handler/inlayHint/index.ts, src/handler/semanticTokens/buffer.ts, src/types.ts
=> feat!: increase minimum vim/nvim versions

src/workspace.ts
The method asRelativePath was probably renamed in the past, however there are extensions such as coc-java which are using the method named asRelativePath expose the method in the workspace api, as it is already exposed in the typings api.
=> fix(workspace): add missing interface to renamed method

data/schema.json, history.md, src/extension/ui.ts
`coc.preferences.extensionUpdateUIInTab`
Closes #5045
=> feat(extension): allow `CocUpdate` UI open in tab

data/schema.json, src/handler/inlayHint/buffer.ts
This PR adds an option to move all inlay hints to *after* the original text.
Personally, I find hints inside the source code very distracting. And they make the code look much wider than it really is, which I personally do not like.
This option allows to restore the old behavior where all hints were displayed at the end of a line.
=> feat(inlayHint): add `inlayHint.position` configuration

autoload/coc/pum.vim
I find that `coc#pum#visible` use `getwinvar(s:pum_winid, 'float', 0) == 1` to check the window. So using `s:pum_winid == -1` may cause problems, now use `coc#pum#visible()` to check if the `pum` is visible.
=> fix(coc#has_item_selected)

autoload/coc/vtext.vim, src/handler/inlayHint/buffer.ts
https://github.com/neoclide/coc.nvim/assets/17562139/645d2e96-ec63-4580-8121-9549403e1017
=> fix(inlayHint): correct gravity for virt_text

src/handler/inlayHint/buffer.ts
Append the last commit
Sorry, I only tested demo without  `nvim.isVim`  condition and forgot to debug again after adding `nvim.isVim` condition.
Mistakenly thinking  `nvim.isVim` is  `nvim.isNvim`.
=> fix(inlayHint): only check condition for Neovim

data/schema.json, doc/coc-config.txt, src/__tests__/client/integration.test.ts, src/diagnostic/buffer.ts, src/diagnostic/manager.ts, src/diagnostic/util.ts, src/language-client/client.ts, src/plugin.ts
See: https://github.com/neoclide/coc.nvim/issues/5086
=> feat(diagnostic): add `showRelatedInformation`

src/list/manager.ts, src/list/ui.ts
=> feat(lsit): add CocListMoved autocmd

data/schema.json, doc/coc-config.txt, history.md, src/language-client/client.ts, src/language-client/features.ts, src/language-client/formatting.ts, src/languages.ts, src/provider/formatManager.ts, src/provider/formatRangeManager.ts, src/services.ts
This is a proof-of-concept.
- Registered by extensions itself (like `coc-pyright`): identified by extension name as expected
- Registered by extensions through a language client (like `@yaegassy/coc-ruff`): identified by extension name as expected
- Registered by coc.nvim for raw LSP `languageserver` configuration: identified as `coc.nvim`
- TODO: So there is no way to select one from multiple LSP - what it should be in this case?
Priorities are still expected to work (when `coc.preferences.formatterExtension` is null).
Closes #5076
=> Add `coc.preferences.formatterExtension` configuration

autoload/coc/util.vim
Vim supports $XDG_CONFIG_HOME as an optional source in [Patch 9.1.0327](https://github.com/vim/vim/commit/c9df1fb35a1866901c32df37dd39c8b39dbdb64a), thus `$XDG_CONFIG_HOME/vim/` will be one of the possible paths of `vimrc`. Therefore, we need to include it as one of the coc configuration paths. Refer to the [patch](https://github.com/vim/vim/commit/c9df1fb35a1866901c32df37dd39c8b39dbdb64a#diff-df93833f5ada39e41ded6f5a6b804b1aa3a75d270848dee769afd9c55f1fcc07R1114-R1117), `$XDG_CONFIG_HOME` will be used as the config path if and only if no other initialization file is found in `$HOME` or `$HOME/.vim`. Consequently, we should first check the `$HOME/.vim`, and the last and default path will be `$HOME/.config/vim`.
=> chore(util): adjust to vim's Patch 9.1.327

src/configuration/index.ts
Currently, we will try to read configuration from disk and leave any exceptions unhandled. This can result in unexpected bailing when the file cannot be read for whatever reason.
This change will ignore such failures, treating them the same as if the path didn't exist.
If you'd rather do this another way, let me know and i'll update
Fixes #5117
=> fix: ignore failed config file reads

data/schema.json, doc/coc-config.txt, history.md, src/handler/codelens/buffer.ts
=> feat(codeLens): add codeLens.display

src/language-client/utils/index.ts
same as VSCode's `new Date().toLocaleTimeString()`
=> feat(language-client): modify log time format

src/list/prompt.ts
=> fix(list): improve regex to remove CJK word

src/list/prompt.ts
Fixes remaining issue in #5134.
This fixes the issue where:
- entire lines are removed on <C-w> even if there are spaces in the middle, and
- the initial spaces are not removed on <C-w>.
=> Improve handling of whitespaces on remove word

src/list/prompt.ts, src/util/string.ts
This is some improvement for #5134.
Sorry for bothering you again. Unfortunately, the previous improvement #5138 does not fix the problem correctly - previous implementation still couldn't remove some ending symbols like '-'. This update introduces more refined word detection logic, similar to Neovim's insert mode behavior.
In addition to the fix of above issue, word boundaries are now detected between characters of different classes, just as in the insert mode. For example, in a Japanese sentence, <C-w> works as follows:
今日はいい天気です
今日はいい天気
今日はいい
今日
This behavior stems from recognizing '気' as an 'ideograph' and 'で' as 'hiragana' - different character classes. I've adopted Neovim's character classification to achieve similar functionality. Note that I'm not meant to achieve completely …
=> Implement insert-mode like word deletion logic in coc lists

data/schema.json, doc/coc-config.txt, doc/coc.txt, history.md
=> docs: mention coc-diagnostics-shim

src/list/manager.ts
`autocmd User CocListMoved echom 'User CocListMoved'`
Closes #5093
=> feat(list): add CocListMoved event

autoload/coc/api.vim
improve performance for large file
(still don't know why this func is called for a buf with b:coc_enabled = 0)
=> improve performance for large file

src/handler/inlayHint/buffer.ts, src/handler/semanticTokens/buffer.ts, src/model/textdocument.ts
From LSP spec [1]:
> .. the end position is exclusive. If you want to specify a range that
> contains a line including the line ending character(s) then use an end
> position denoting the start of the next line.
but it doesn't mention what we should send to server if the file hasn't EOL. VS Code will set end = { line = last line number (0-based), character = length of the last line}. This fix will change the behavior to the same as VS Code so that some language servers (such as roslyn language server) will work normally.
[1] https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range
=> fix(inlayHint&semanticTokens): Fix range send to server

src/__tests__/handler/semanticTokens.test.ts, src/handler/semanticTokens/buffer.ts
From `[start-height*1.5, end+height*1.5]` to `[start-height/2, end+height/2]`, decrease items count to highlight.
Related #5199, should reduce flickering happened
=> feat(semanticTokens): decrease highlighting range

src/handler/semanticTokens/buffer.ts
=> fix(semanticTokens): correct end range

autoload/coc/highlight.vim, doc/coc.txt, src/handler/semanticTokens/buffer.ts
Closes #5199
- https://github.com/neoclide/coc.nvim/pull/5205
- https://github.com/neoclide/coc.nvim/pull/5206
=> perf(highlight): increase number of highlights

src/plugin.ts
- This changes the message from `Action ${...} not exist` to `Action ${...} does not exist` which seems consistent with the gramma of other error messages.
[skip ci]
=> fix(plugin): gramma on Action not existing

autoload/coc/vtext.vim
From vim doc [1]:
Any Tab and other control character in the text will be changed to a space (Rationale: otherwise the size of the text is difficult to compute).
If we use tabs as indent, then the code lens will be misaligned with the real text even if we set the indent of the code lens to the right number of tabs.
[1] https://vimhelp.org/textprop.txt.html#virtual-text
=> fix(codeLens): Misalign when using tabs as indent

autoload/coc/float.vim, data/schema.json, doc/coc-config.txt, src/model/floatFactory.ts, typings/index.d.ts
This PR adds a new feature to support fixed positioning for floating windows.
Sometimes while coding, I find the diagnostic floating windows can be distracting as they often overlap with the code I'm trying to read. Many diagnostics are temporary and appear during the coding process, and I don't always need to see these less important diagnostic messages. However, they still pop up large floating windows that disrupt my focus.
I took inspiration from Helix editor's diagnostic design, which displays the current cursor's diagnostic message in a fixed position at the top-right corner of the editor. I find this design very effective as it keeps the main editing area clean and uncluttered.
This implementation allows for a more focused coding experience.
=> feat: add fixed position support for floating windows

src/language-client/index.ts
=> fix(client): `shell=true` on windows

data/schema.json, doc/coc.txt, history.md, lua/coc/diagnostic.lua, plugin/coc.vim, src/__tests__/modules/diagnosticManager.test.ts, src/diagnostic/buffer.ts, src/diagnostic/util.ts
The `diagnostic.displayByVimDiagnostic` configuration will set diagnostics to nvim's `vim.diagnostic`, and prevent coc.nvim's handler to display them in virtualText/sign/floating etc.
=> feat(diagnostic): add `diagnostic.displayByVimDiagnostic`

src/__tests__/modules/diagnosticManager.test.ts, src/diagnostic/buffer.ts
=> fix(diagnostic): only set coc_diagnostic_map on displayByVimDiagnostic

src/completion/source-language.ts
Closes https://github.com/fannheyward/coc-xml/issues/519
=> feat(completion): support `textEditText`

doc/coc.txt
When the `BufAdd` event triggers, `<afile>` is not yet entered. So `b:coc_enabled = 0` is set to the wrong buffer, the one before you switch to the new buffer. The event should be `BufRead`.
=> docs: use BufRead in b:coc_enabled example

bin/prompt.js
changing the octal escape sequence `\033` to hexadecimal `\x1b`, as tsserver reported error:
`Octal escape sequences are not allowed. Use the syntax '\x1b'`
=> fix(prompt): correct format of escape sequence

.github/workflows/ci.yml, autoload/coc/api.vim, autoload/coc/highlight.vim, vim9/coc/highlight.vim
Resolves #5199
Ports some slow functions to `:def` functions.
```vim
FUNCTIONS SORTED ON SELF TIME
count     total (s)      self (s)  function
17513   0.674963885   0.579616606  54()
17513   1.112946488   0.382665796  coc#highlight#add_highlight()
17   0.304494455   0.304348708  coc#highlight#del_markers()
45   1.296966406   0.186026396  <SNR>155_add_highlights()
21   0.204020373   0.159163633  coc#highlight#get_highlights()
17513                 0.095347279  <SNR>50_generate_id()
14798                 0.044771580  <SNR>155_prop_type_hlgroup()
FUNCTIONS SORTED ON SELF TIME
count     total (s)      self (s)  function
17                 0.237726631  <SNR>156_Del_markers()
17513   0.067899809   0.055712181  coc#api#funcs_buf_add_highlight()
19   0.046720607   0.027843561 …
```
=> Improve Vim9 highlight performance

autoload/coc/dialog.vim, autoload/coc/float.vim, data/schema.json, src/__tests__/modules/menu.test.ts, src/completion/pum.ts, src/model/dialog.ts, src/model/input.ts
This makes use of the `CocFloatBorder` highlight group introduced in d825dbae9e59fb17a64d172b779ea8bc795aecf5. See also #5298. Without these changes, the `CocFloatBorder` highlight group is not used.
I searched the codebase for usage of `CocFloating` and replaced it with `CocFloatBorder` where it looked to me like it would be appropriate. I might have missed some spots and maybe not all changes in the PR should be applied.
=> Make use of the new CocFloatBorder highlight group

autoload/coc/float.vim
If no other value is set for `borderhighlight`, use the default `CocFloatBorder`.
=> Use `CocFloatBorder` by default

autoload/coc/vtext.vim
Benchmark with `:profile` on a large file(`build/index.js`) after multiple `500j`:
```vim
FUNCTIONS SORTED ON SELF TIME
count     total (s)      self (s)  function
2024   0.203985531   0.169318569  coc#vtext#add()    " Before
2024   0.096831518   0.075034772  coc#vtext#add()    " After
```
Profile log shows the total time is almost twice the time of the lines added up, not sure why. <br>
`coc#vtext#add` is called by `coc#api s:call_atomic`, which on each call executes `coc#vtext#add` multiple times.
Benchmark with `reltime(`: 
<details>
<summary>steps</summary>
Apply this patch, then open `build/index.js` and wait for outputs of `:echom`
```diff
diff --git a/autoload/coc/api.vim b/autoload/coc/api.vim
index d62f040..ba52e9c 100644
--- a/autoload/coc/api.vim
+++ b/autoload/coc/api.vim
@@ …
```
=> refactor(vtext, vim9): Port `coc#vtext#add` to `:def` function

autoload/coc/vim9.vim, autoload/coc/vtext.vim
cc @atitcreate
https://github.com/neoclide/coc.nvim/commit/a277167aa523983c3f647be448f717276def5ed8#diff-2ecbe67c0b76275c0dddfecefdb420b8489f480c51a8a792518164129dcd7390
=> fix(vim9): correct tabSize

plugin/coc.vim
When attempting to open new directory as buffer, I'd bump into the below error message:
> Error detected while processing function <SNR>1_opendir[4]..BufEnter Autocommands for "*"..function <SNR>82_HandleBufEnter:
line    3:
E158: Invalid buffer name: 25
My interpretation of the error is that something on the Coc side is trying to interpret the buffer number (25) as a buffer name (a path string), and fails when the buffer is invalid (e.g., it's a directory or not yet fully loaded). Adding the conditions to guard against unlisted or invalid buffers.
=> Guard against unlisted or invalid buffers

src/core/autocmds.ts
autocmd is broken with latest update
```
2025-05-04T14:50:45.339 ERROR (pid:17884) [node-client] - Error event from nvim: [33m1[39m Invalid 'event': 'CursorMoved,CursorMovedI'
```
=> feat(autocmd): backwards compatible

autoload/coc/util.vim
When jumping within the same file opened in multiple windows (e.g. via `:vsplit`),
`:call CocAction('jumpDefinition', 'drop')` may switch to the first window containing the buffer, causing the jump
to land in a different window than the user's current one.
This change adds a check to avoid running `drop` when the target buffer is already the current one, improving the UX in split-window navigation.
Before:
https://github.com/user-attachments/assets/9ec99106-0e26-44a6-9012-6d2a8e7ecef3
After:
https://github.com/user-attachments/assets/d8fd8e2b-4f15-4834-b7a9-4b3d3fdcd366
=> fix(jump): avoid 'drop' stealing focus in multi-window same-buffer jumps

README.md
> Add a badge to this wiki in the repo's README file to auto refresh the wiki weekly with the latest code. [Create badge](https://deepwiki.com/badge-maker?url=https%3A%2F%2Fdeepwiki.com%2Fneoclide%2Fcoc.nvim)
=> docs: add deepwiki badge to readme

autoload/coc/float.vim
Problem: completion document floating window couldn't be closed in nvim nightly
Reason: https://github.com/neovim/neovim/pull/34207 `winnr('$')` will skip to return focusable=false window
Use `nvim_list_wins` to get all window-ids.
I've checked other `winnr('$')` usage, didn't find any problems for now, so I don't change them.
=> fix(float): use nvim_list_wins to get all winids

autoload/coc/vim9.vim
=> fix(vim9): move cursor after applyEdits

src/__tests__/core/workspaceFolder.test.ts, src/core/workspaceFolder.ts
Previously, `rootPatterns` defined for custom language servers would not be picked up by coc.nvim. For example, if I have this in my configuration:
```vim
autocmd User CocNvimInit call coc#config('languageserver.lua_ls', {
\ 'filetypes': ['lua'],
\ 'command': 'lua-language-server',
\ 'rootPatterns': ['.luarc.json', '.luarc.jsonc'],
\ 'settings': { 'Lua': coc#util#get_config('Lua') },
\ })
```
and if I run `echo coc#util#root_patterns()` in a Lua buffer, I would get
```vim
{'global': ['.vim', '.git', '.hg', '.projections.json'], 'buffer': [], 'server': []}
```
which is clearly wrong. With my PR, I now get:
```vim
{'global': ['.vim', '.git', '.hg', '.projections.json'], 'buffer': [], 'server': ['.luarc.json', '.luarc.jsonc']}
```
=> fix(workspaceFolder): load rootPatterns of user-defined language servers

autoload/coc/util.vim
Simulated the events triggered by tab drop when jumping to the target page:
- Added events for leaving the tab.
- Added buffer-related events, as some plugins will depend on these events.
- Fix the problem of no events when navigating within one tab
=> fix(jump): improve the events for `tab drop`

history.md, src/__tests__/modules/extensionInstaller.test.ts, src/__tests__/modules/extensionManager.test.ts, src/extension/installer.ts, src/extension/manager.ts, src/extension/stat.ts
extension can set `extensionDependencies` in package.json to declare dependencies on other extensions. coc.nvim will install the dependencies, and activate dependencies first before active the main extension.
cc @statiolake, you might need this, please give it a try
=> feat(extension): support extensionDependencies

lua/coc/highlight.lua
=> fix(highlight): improve table checking

src/model/document.ts
in b6d9e5263e04bf593218b3215bf334a4f2a904cd, coc.nvim uses `pumInserted` to prevent document synchronize instead of completing, this fix revert to use `completing`, and leave inline completion to use pumInserted
Closes #5415
=> fix(event): use completing to prevent synchronize

autoload/coc/util.vim
`BufRead` and `BufReadPost` are synonyms.
=> fix(jump): Remove the duplicated `BufRead` event
